(function(a){a&&a.deps.addDependency("personalprod.oldLife",["personalprod.oldLife-1.0.js"])})("undefined"==typeof arale?void 0:arale);
AP.pk.pa.popup=function(a,b,d,e,c,f){var g="string"===typeof a?D.get(a):a,h="string"===typeof b?D.get(b):b,d=""!==d?d:"click",k=this,f=f||D.get("container");k.container=b;if(!("undefined"==g||null==g||"undefined"==h||null==h)&&"hover"===d)E.on(g,"click",function(a){"A"===g.tagName.toUpperCase()&&E.preventDefault(a)}),E.on(g,"mouseover",function(){D.removeClass(h,"fn-hide");D.setXY(b,[D.getX(g),D.getRegion(g).bottom]);D.getRegion(b).right>D.getRegion(f).right&&D.setXY(b,[D.getX(g)-(D.getRegion(b).right-
D.getRegion(f).right)-30,D.getRegion(g).bottom]);e&&e(k)}),E.on(g,"mouseout",function(a){AP.fn.eInRegion(D.getRegion(h),a)||(D.addClass(h,"fn-hide"),c&&c(k))}),E.on(h,"mouseout",function(a){AP.fn.eInRegion(D.getRegion(h),a)||(D.addClass(h,"fn-hide"),c&&c(k))})};
AP.pk.pa.countText=function(a,b,d,e){if(a.value.length>e)return d.innerHTML="\u5907\u6ce8\u5b57\u6570\u5df2\u7ecf\u8d85\u8fc7"+e+"\u7684\u9650\u5236",b.innerHTML="0",D.addClass(a.parentNode,"fm-error"),!1;b.innerHTML=e-a.value.length;D.removeClass(a.parentNode,"fm-error");return!0};AP.pk.pa.TextCounter=function(a,b,d,e){E.on(a,"keyup",function(){AP.pk.pa.countText(a,b,d,e)});E.onDOMReady(function(){AP.pk.pa.countText(a,b,d,e)})};
AP.pk.pa.TextMagnifier=function(a,b){function d(){for(var b=a.value,b=b.trimAll(),d=b.substring(0,3),b=b.substring(3);b&&0<b.length;)d+=" "+b.substring(0,4),b=b.substring(4);c.innerHTML=d}function e(){D.removeClass(b,"fn-hide");D.setXY(b,[D.getX(a),D.getRegion(a).bottom])}var c=D.query(".mag-text",b)[0];E.on(a,"keyup",function(){0==a.value.length?D.addClass(b,"fn-hide"):e();d()});E.on(a,"blur",function(){D.addClass(b,"fn-hide");a.value=a.value.trimAll()});E.on(a,"focus",function(){0<a.value.length&&
(e(),d())})};AP.pk.pa.isValidAmount=function(a){"string"==typeof a&&(a=a.trim());return!isNaN(parseFloat(a))&&1E10>parseFloat(a)&&/^\d+(\.\d{0,2})?$/.test(a)?!0:!1};AP.pk.pa.isInteger=function(a){return AP.pk.pa.isValidAmount(a)&&/^[1-9][0-9]*$/.test(a)};
AP.pk.pa.toggle=function(a,b,d,e,c,f){if("input"==a.nodeName.toLowerCase()&&"checkbox"==a.type)E.on(a,"click",function(){a.checked?(D.removeClass(b,"fn-hide"),c&&c()):(D.addClass(b,"fn-hide"),f&&f())});else E.on(a,"click",function(g){if(0==b.offsetWidth){D.removeClass(b,"fn-hide");if(e)a.innerHTML=e;c&&c()}else{D.addClass(b,"fn-hide");if(d)a.innerHTML=d;f&&f()}E.preventDefault(g)})};
AP.pk.pa.formatMonth=function(a){for(var b=a.split(","),a={},d=0;d<b.length;d++){var e=b[d],c=e.substring(0,4),e=e.substring(4);a[c]||(a[c]=[]);a[c].push(e)}b={};for(year in a){d=a[year];c="";if(12==d.length)c="\u5168\u5e74";else{for(var f=0;f<d.length;)if(e=parseInt(d[f],10),f+2<d.length)if(2<parseInt(d[f+2],10)-e)c+=e+"\u3001",f++;else{for(var g="";f<d.length-1&&parseInt(d[f],10)+1==parseInt(d[f+1],10);)g=parseInt(d[f+1],10),f++;"\u3001"==c.charAt(c.length-1)&&"\u6708"!=c.charAt(c.length-2)&&(c=
c.substring(0,c.length-1)+"\u6708\u3001");c+=e+"-"+g+"\u6708\u3001";f+=1}else c+=e+"\u3001",f++;"\u3001"==c.charAt(c.length-1)&&"\u6708"!=c.charAt(c.length-2)&&(c=c.substring(0,c.length-1)+"\u6708");"\u3001"==c.charAt(c.length-1)&&(c=c.substring(0,c.length-1))}b[year]=c}return b};
AP.pk.pa.contactsAutoComplete=function(a){var b;a.apiUrl?(b=new YAHOO.util.ScriptNodeDataSource(a.apiUrl+"/user/contacts/searchResult.json?"),b.scriptCallbackParam="_callback"):b=new YAHOO.util.XHRDataSource("/user/contacts/searchResult.json");b.responseType=YAHOO.util.XHRDataSource.TYPE_JSON;b.connMethodPost=!0;b.maxCacheEntries=60;b.responseSchema={resultsList:"result",fields:["contactLogonId","contactNickName","ownerCardNo","contactRealName","id"]};b=new YAHOO.widget.AutoComplete(a.inputEl,"autoCompleteContainer",
b);b.queryDelay=0;b.resultTypeList=!1;b.autoHighlight=!1;b.generateRequest=function(a){return"keyword="+a};b.formatResult=function(a){var b=D.query("#autoCompleteContainer ul")[0];D.setStyle(b,"width","174px");D.setStyles(b,{display:""});b=a.contactNickName?a.contactNickName:"";if(a.contactRealName){var c=a.contactRealName;8<c.len()&&(c=c.brief(8)+"..")}else c="";a=a.contactLogonId;16<a.len()&&(a=a.brief(16)+"..");return'<span title="'+b+'" rel="'+a+'">'+c+"("+a+")</span>"};b.itemSelectEvent.subscribe(function(b,
e){a.selectHandler(e[2])});b.dataErrorEvent.subscribe(function(){var a=D.query("#autoCompleteContainer ul")[0];D.setStyles(a,{display:"none"})});b.containerExpandEvent.subscribe(function(a,b){a=b[0];D.setXY(D.query(".yui-ac-content .yui-ac-bd",a.getContainerEl())[0],[D.getX(a.getInputEl()),D.getRegion(a.getInputEl()).bottom])});return b};AP.pk.pa.life=AP.pk.pa.life?AP.pk.pa.life:{};
AP.pk.pa.life.calculateExtraFee=function(a,b){function d(a){e.innerHTML=a;0<parseFloat(a)?D.removeClass(c,"fn-hide"):D.addClass(c,"fn-hide")}var e=D.get("extraFee"),c=D.get("extraFeeWrapper"),f=b.extraFeeProp,g=b.isWhiteUser,h=b.accountInput.value,k=f.amountLeft,m=b.isToAli||function(){return!0};if(m()&&f.useRate&&!g){if(AP.pk.pa.isValidAmount(a)&&a>k){var j=(Math.round((100*parseFloat(a)-100*parseFloat(k))*(f.rate/100))/100).toFixed(2);1>j?j="1.00":25<j&&(j="25.00")}d(j)}else AP.pk.pa.isValidAmount(a)?
(g=m()?"0":"1",f={onAPISuccess:function(a,b){d(b[0].fee)},onAPIFailure:function(){D.addClass(c,"fn-hide")},method:"POST"},b.extraFeeUrl&&AP.hashExtend(f,{api_url:b.extraFeeUrl,format:"jsonp"}),h={amount:a,account:h,payType:g},b.isAliToCard&&(g=b.isAliToCard()?"0":"1",AP.hashExtend(h,{transferMode:g})),(new AP.core.api("life/getExtraFee",f)).call(h)):D.addClass(c,"fn-hide")};
AP.pk.pa.life.AmountInput=function(a,b){function d(){var b=D.get("cellphoneField");1<=parseFloat(a.value)?(D.get("smsAlert").disabled=!1,D.removeClass("smsLabel","ft-gray"),D.get("smsAlert").checked&&D.removeClass(b,"fn-hide")):(D.addClass("smsLabel","ft-gray"),D.get("smsAlert").checked=!1,D.get("smsAlert").disabled=!0,D.addClass(b,"fn-hide"))}if(!b.isToAli)b.isToAli=function(){return!0},b.isAliToCard=function(){return!1};var e=b.extraFeeProp;E.on(a,"blur",function(){(!e.useRate||b.isWhiteUser||!b.isToAli())&&
AP.pk.pa.life.calculateExtraFee(a.value,b);d()});E.onDOMReady(function(){d()})};AP.pk.pa.life.freeSmsTrigger=function(a){function b(){var b=D.get("cellphoneField");1<=parseFloat(a.value)?(D.get("smsAlert").disabled=!1,D.removeClass("smsLabel","ft-gray"),D.get("smsAlert").checked&&D.removeClass(b,"fn-hide")):(D.addClass("smsLabel","ft-gray"),D.get("smsAlert").checked=!1,D.get("smsAlert").disabled=!0,D.addClass(b,"fn-hide"))}E.on(a,"keyup",function(){b()});E.on(a,"blur",function(){b()});E.onDOMReady(function(){b()})};
AP.pk.pa.AddToContacts=function(a){function b(a){D.removeClass(a,"fn-hide")}function d(a){D.addClass(a,"fn-hide")}new AP.widget.appendToGroup({completeEvent:function(){D.removeClass(D.get("addToContacts"),"no-group");b("clearSelection")},apiUrl:a.apiUrl});E.on("chooseGroups","click",function(){0<D.query("a.selected",D.get("chooseGroups")).length?b("clearSelection"):d("clearSelection")});AP.widget.formInputStyle.init(D.get("groupTxt"));E.on(["createGroupBtn","cannelChoose"],"click",function(a){E.preventDefault(a)});
E.on("doAddContact","click",function(){function b(c){var d=[],e=[];D.query("a.selected",D.get("chooseGroups")).forEach(function(a){d.push(a.getAttribute("rel"));e.push(D.query("span",a)[0].innerHTML)});c&&(d.push(c.id),e.push(c.name));D.get("groupIds").value=d.join(",");e.join(",");c={onAPISuccess:function(b,c){a.onSuccess(c[0])},onAPIFailure:function(){},method:"POST"};a.apiUrl&&AP.hashExtend(c,{api_url:a.apiUrl,format:"jsonp"});var c=new AP.core.api("user/contacts/addToGroups",c),f=D.get("groupIds").value,
g=[];D.query("input[name=emails]").forEach(function(a){a.checked&&g.push(a.value)});logonIds=g.join(",");c.call({groupIds:f,logonIds:logonIds})}for(var c=D.query("#addToContacts input[name=emails]"),d=!0,g=0;g<c.length;g++)if(c[g].checked){d=!1;break}d?D.addClass("addToContacts","no-selection"):(D.removeClass("addToContacts","no-selection"),D.get("groupTxt")&&0<D.get("groupTxt").offsetHeight&&D.get("groupTxt").value?(c={onAPISuccess:function(a,c){c=c[0];b({id:c.result.id,name:c.result.name})},onAPIFailure:function(a,
b){var c=D.get("groupTxt").parentNode;D.query(".fm-explain",c)[0].innerHTML=b[0].msg;D.addClass(c,"fm-error")},method:"POST"},a.apiUrl&&AP.hashExtend(c,{api_url:a.apiUrl,format:"jsonp"}),(new AP.core.api("user/contacts/createGroup",c)).call({groupName:D.get("groupTxt").value})):b())});E.on("cancelAddToContacts","click",function(){b(D.get("addContactNotice"));d(D.get("addToContacts"))});E.on("clearSelection","click",function(a){D.query("a.selected",D.get("chooseGroups")).forEach(function(a){D.removeClass(a,
"selected")});d("clearSelection");E.preventDefault(a)})};
AP.pk.pa.BankBranchSelector=function(a){function b(){var a=g.value,b=f.value,d=c.value;a&&b&&d?e(a,b,d):h.value=m}function d(){h.style.width="150px";j.style.width="175px"}function e(b,c,e){var f={onAPISuccess:function(a,b){var b=b[0],c=b.branches;if(c&&0<c.length){if(-1==c.indexOf(h.value))h.value=m;AP.cache._ACDS.liveData=c;for(var f=D.query(".yui-ac-content .yui-ac-bd ul",oAC.getContainerEl())[0].style,e=c[0],g=1;g<c.length;g++)c[g].length>e.length&&(e=c[g]);f.width=12.5*e.length+20+"px";D.removeClass(l,
"fn-hide");h.disabled=!1}else D.addClass(l,"fn-hide"),h.value="\u6ca1\u6709\u8be5\u5730\u533a\u652f\u884c\u4fe1\u606f",h.disabled=!0,d()},onAPIFailure:function(){},method:"POST"};a.apiUrl&&AP.hashExtend(f,{api_url:a.apiUrl,format:"jsonp"});f=new AP.core.api(k,f);c=-1<["\u5317\u4eac","\u4e0a\u6d77","\u91cd\u5e86","\u5929\u6d25"].indexOf(c)?c+"\u5e02":c;f.call({bank:b,prov:c,city:e})}var c=a.cityInput,f=a.provInput,g=a.bankInput,h=a.branchInput,k=a.branchUrl,m=a.tipText||"\u8bf7\u9009\u62e9\u652f\u884c",
j=a.container||h.parentNode,l=D.get("comboboxBtn"),q=D.get("comboAcContainer");E.onDOMReady(function(){b()});this.reloadBranches=b;oAC=function(){function a(b){h.value=b;150>12.5*b?d():(h.style.width=12.5*b.length+"px",j.style.width=12.5*b.length+30+"px")}AP.cache._ACDS=new YAHOO.util.LocalDataSource([]);var b=new YAHOO.widget.AutoComplete(h,q,AP.cache._ACDS,{prehighlightClassName:"yui-ac-prehighlight",queryDelay:0,minQueryLength:0,queryMatchContains:!0,maxResultsDisplayed:500,animVert:!1});b.setFooter("<span id='comboShowAll'>\u67e5\u770b\u5168\u90e8</span>");
D.get("comboShowAll");E.on(l,"click",function(){b.isContainerOpen()?b.collapseContainer():setTimeout(function(){b.sendQuery("")},0)});E.on(h,"blur",function(){if(-1==AP.cache._ACDS.liveData.indexOf(h.value)){var b="";c[0]?b=c[0]:0<AP.cache._ACDS.liveData.length&&(b=AP.cache._ACDS.liveData[0]);a(b)}});E.on(h,"click",function(){setTimeout(function(){b.sendQuery("")},10)});b.itemSelectEvent.subscribe(function(b,c){var d=c[0];a(c[2][0]);d.getInputEl().blur()});b.containerExpandEvent.subscribe(function(a,
b){var a=b[0],c=D.get("comboShowAll").parentNode;D.addClass(c,"fn-hide");var d=D.query(".yui-ac-content .yui-ac-bd",a.getContainerEl())[0];D.setXY(d,[D.getX(j),D.getRegion(j).bottom]);c=D.query(".yui-ac-content .yui-ac-ft",a.getContainerEl())[0];D.setXY(c,[D.getX(d),D.getRegion(d).bottom])});var c=[];b.dataReturnEvent.subscribe(function(a,b){c=b[2]});return b}();var n=D.get("comboShowAll");E.on(n,"click",function(){oAC.sendQuery("")});E.on(document.body,"click",function(a){!AP.fn.eInRegion(D.getRegion(h),
a)&&!AP.fn.eInRegion(D.getRegion(j),a)&&oAC.collapseContainer()})};AP.pk.pa.life.toggleFee=function(a,b){var d="fee-toaccount";b.isToAli()||(d=b.isAliToCard()?"fee-accounttocard":"fee-banktocard");D.removeClass(a,"fee-toaccount");D.removeClass(a,"fee-accounttocard");D.removeClass(a,"fee-banktocard");D.addClass(a,d)};
function initToCard(a){function b(a){D.removeClass(a,"fn-hide")}function d(a){D.addClass(a,"fn-hide")}function e(){return D.hasClass("alipayTab","current")}function c(){return D.get("aliRadio").checked}function f(a){D.removeClass(a.parentNode,"fm-error");D.query(".fm-explain",a.parentNode)[0].innerHTML=a.getAttribute("data-explain")||""}function g(a){AP.widget.unfamiliarWords&&new AP.widget.unfamiliarWords(a,{selectEvent:function(a,b){p.value+=b[0].innerHTML;b[2].hide();p.focus()},showEvent:function(){},
offset:[-210,0],class_name:"unfamiliarTag"})}function h(){c()?(D.addClass("payMethodItem","from-account"),D.removeClass("payMethodItem","from-card")):(D.removeClass("payMethodItem","from-account"),D.addClass("payMethodItem","from-card"));f(D.get("amount"));d(l)}function k(a,b){(new AP.core.api("bank/validateCard",{onAPISuccess:function(){f(D.get("bankCardNo"))},onAPIFailure:function(a,b){var b=b[0],c=D.get("bankCardNo"),d=b.msg;D.addClass(c.parentNode,"fm-error");D.query(".fm-explain",c.parentNode)[0].innerHTML=
d},method:"POST"})).call({bankName:a,cardNo:b.trimAll()})}function m(a){(new AP.core.api("bank/validateTransferBank",{onAPISuccess:function(c,e){e=e[0];"false"==e.needBranch?(d("branchItem"),o=!1,n.value="",D.get("branchDisplay").innerHTML=""):(b("branchItem"),o=!0,r.reloadBranches());var f=D.get("bankCardNo").value;f&&k(a,f)},onAPIFailure:function(){},method:"POST"})).call({bankName:a})}a.isToAli=e;a.isAliToCard=c;var j=D.get("amount"),l=D.getNextSiblingBy(j,function(a){return D.hasClass(a,"fm-explain")}),
q=j.getAttribute("data-explain"),n=D.get("comboboxInput"),o=n.value&&0<n.offsetHeight?!0:!1;new AP.widget.tabSwitch(D.query("#J-tab li"),{onAfter:function(){e()?(d("payMethodItem"),b(l),j.setAttribute("data-explain",q),f(j)):(b("payMethodItem"),d(l),j.setAttribute("data-explain",""));AP.pk.pa.life.calculateExtraFee(D.get("amount").value,a)}});!e()&&!D.hasClass(l.parentNode,"fm-error")&&d(l);E.on(j,"focus",function(){d(l)});var p=D.get("bankCardName");try{g(D.query(".unfamiliarTag"))}catch(t){log(t)}E.on(p,
"focus",function(){setTimeout(function(){try{g(D.query(".unfamiliarTag"))}catch(a){log(a)}},1E3)});new AP.widget.reviewCardID(D.query(".J-bank-card"));new AP.widget.dropDown(D.query(".J-history"),{isposition:!1,targetClick:function(){var a=D.getRegion("showHistory");D.setXY("showHistoryExtend",[a.left,a.bottom]);if(5<D.query("#showHistoryExtend dd").length)D.query("#showHistoryExtend .optional")[0].style.height="100px"}});D.query("#showHistoryExtend dd a.J-history-item").forEach(function(a){E.on(a,
"click",function(c){D.get("bankCardName").value=D.get("bankCardNameDisplay").innerHTML=a.getAttribute("cardname");D.get("bankCardNo").value=D.get("bankCardNoDisplay").innerHTML=a.getAttribute("cardno");D.get("bankNameDisplay").innerHTML=a.getAttribute("bankname");D.get("bankName").value=a.getAttribute("bankShortName");D.get("locationDisplay").innerHTML=a.getAttribute("prov")+a.getAttribute("city");D.get("prov-input").value=a.getAttribute("prov");D.get("city-input").value=a.getAttribute("city");s.setData([D.get("prov-input").value,
D.get("city-input").value]);var e=a.getAttribute("branch");e?(D.get("comboboxInput").value=D.get("branchDisplay").innerHTML=e,b("branchItem"),o=!0):(D.get("comboboxInput").value=D.get("branchDisplay").innerHTML="",d("branchItem"),o=!1);D.removeClass("bankCardExtend","history-off");D.addClass("showHistoryExtend","fn-hide");try{D.addClass("bankCardExtend","history-on")}catch(f){log(f)}E.preventDefault(c)})});E.on(D.query(".J-modifyHistory"),"click",function(a){E.preventDefault(a);D.removeClass(D.get("bankCardExtend"),
"history-on");D.addClass(D.get("bankCardExtend"),"history-off")});E.on("bankCardNo","blur",function(){var a=D.get("bankCardNo").value,b=D.get("bankName").value;b&&a&&k(b,a)});E.on("bankName","change",function(){m(D.get("bankName").value);D.get("city-input").setAttribute("data-explain","");f(D.get("city-input"))});E.on("aliRadio","click",function(){AP.pk.pa.life.calculateExtraFee(D.get("amount").value,a);h()});E.on("bankRadio","click",function(){AP.pk.pa.life.calculateExtraFee(D.get("amount").value,
a);h()});var s=new AP.widget.cityHint({key:"cityhint",triggle:["cityhint-city-select"],units:!0,onCitySelect:function(){o&&(r.reloadBranches(),b("branchItem"))}});s.render();var r=new AP.pk.pa.BankBranchSelector({cityInput:D.get("city-input"),provInput:D.get("prov-input"),bankInput:D.get("bankName"),branchInput:D.get("comboboxInput"),branchUrl:"bank/getBranches"})}
AP.pk.IframeOverlay=function(a){var b=D.get("iframe-overlay");b||(b=Element.create("iframe"),b.setAttribute("frameborder","0"),b.setAttribute("scrolling","no"),b.setAttribute("src",'javascript:""'),D.setStyles(b,{position:"absolute",background:"#fff",padding:"0",display:"none",width:a.offsetWidth+"px",height:a.offsetHeight+"px"}),D.insertBefore(b,a));this.show=function(){b.style.display="block";b.style.width=a.offsetWidth+"px";b.style.height=a.offsetHeight+"px";D.setXY(b,D.getXY(a))};this.hide=function(){b.style.display=
"none"}};AP.pk.pa.placeholder=function(a){if(!AP.pk.pa.placeholder.isSupport()){var b=a.getAttribute("placeholder");E.on(a,"focus",function(){if(this.value==b)this.value="",D.removeClass(this,"hasPlaceholder")});E.on(a,"blur",function(){if(""==this.value||this.value==b)this.value=b,D.addClass(this,"hasPlaceholder")});if(""==a.value||this.value==b)a.value=b,D.addClass(a,"hasPlaceholder")}};AP.pk.pa.placeholder.isSupport=function(){i=document.createElement("input");return"placeholder"in i};
