light.has("/alipay/security/riskMobileCredit")||function(b,k){try{window==window.parent&&b.client.storage.set("riskMobileCreditSendTime",-1)}catch(i){}var a={Name:"riskMobileCredit",defaults:{id:"",autoSend:!0,isBind:"",ajaxUrl:"",countdownBefore:null,countdownAfter:null,requestBefore:null,requestAfter:null}},h={sms:{className:".sms-btn",btnText:"\u91cd\u65b0\u83b7\u53d6\u77ed\u4fe1",interval:120,prompt_send:"\u6821\u9a8c\u7801\u5df2\u53d1\u9001\uff0c30\u5206\u949f\u5185\u8f93\u5165\u6709\u6548\uff0c\u8bf7\u52ff\u6cc4\u9732",
prompt_default:"\u6821\u9a8c\u7801\u662f6\u4f4d\u6570\u5b57\uff0c30\u5206\u949f\u5185\u8f93\u5165\u6709\u6548\uff0c\u8bf7\u52ff\u6cc4\u9732"},phone:{className:".phone-btn",btnText:"\u4f7f\u7528\u8bed\u97f3\u83b7\u53d6",interval:120,prompt_send:"\u652f\u4ed8\u5b9d\u5c06\u5411\u60a8\u7684\u624b\u673a\u62e8\u6253\u7535\u8bdd\u5e76\u64ad\u62a5\u6821\u9a8c\u7801\u3002<br />\u6765\u7535\u53f7\u7801\u4e3a\uff1a0571-26883721,\u8bf7\u7a0d\u5019...",prompt_default:"\u6821\u9a8c\u7801\u662f6\u4f4d\u6570\u5b57\uff0c30\u5206\u949f\u5185\u8f93\u5165\u6709\u6548\uff0c\u8bf7\u52ff\u6cc4\u9732"}};
a.properties={targets:[],count:!0};a=b.register("/alipay/security/riskMobileCredit",window,b.deriveFrom(k.base,{ready:!0,render:function(c){b.isFunction(c)&&this._readyList.push(c);this.element=this.options.uniqElement;for(c=this._readyList;c.length;)c.shift().apply(this)},getValue:function(){return{mobileAckCode:this.element.value}},postInit:function(){var c=this,a=this.options;this.container=b.node(this.options.uniqElement).parent(".ui-form-item");this.itemExp=this.container.find(".ui-form-explain");
b.each(h,function(b,f){var g=c.container.find(f.className);g.length&&(g.type=b,!a.defaultType&&(a.defaultType=b),c.targets.push(g))});this.targets.length||b.log("No mode used.");a.autoSend&&this.request("sms");this.bind()},bind:function(){var c=this,a=this.options;this.options.autoSend||this.container.find(".send-btn").click(function(){b.node(this).addClass("fn-hide");c.container.find(".ui-form-field, .ui-form-explain").removeClass("fn-hide");c.request("sms")});this.container.find(".reSend-btn").click(function(e){e.cancel();
b.node(this).addClass("fn-hide");c.container.find(".sms-btn, .phone-btn").removeClass("fn-hide");c.sendSuccess(a.defaultType);c.countdown(a.defaultType)});b.each(this.targets,function(a,b){b.click(function(){c.send(b.type)})});b.ready(function(){b.node(".phone-btn").length&&(c.pop=new b.pop({targets:b.node(".phone-btn"),className:"ui-securitycore",width:400}))})},send:function(a){a=a||this.options.defaultType;this.countdown(a);this.request(a)},countdown:function(a){var b=this,e=b.options,a=a||e.defaultType,
f=h[a].interval;e.countdownBefore&&e.countdownBefore();(function(){0<f--&&b.riskCredibleMobile.expand?(b.toggleBtnUI(f),setTimeout(arguments.callee,1E3)):(b.updatePrompt(a,"prompt_default"),b.toggleBtnUI(f,!0),b.container.removeClass("ui-form-item-success"),e.countdownAfter&&e.countdownAfter())})()},toggleBtnUI:function(a,d){var e=this,f,g=d?"removeClass":"addClass";b.each(this.targets,function(b,j){f=d?h[j.type].btnText:"\uff08"+a+"\u79d2\u540e\uff09"+h[j.type].btnText;d||e.pop&&e.pop.hide();j[g]("ui-checkcode-messagecode-disabled-btn").attr("disabled",
!d).attr("value",f)})},updatePrompt:function(a,b){this.container.find(".ui-form-explain").html(h[a][b])},request:function(a){if(window!=window.parent){var d=(new Date).getTime(),e=Number(b.client.storage.get("riskMobileCreditSendTime"));if(0>d-e){this.sendSuccess(a);return}}var f=this,g=this.options,d={},a=a||g.defaultType;g.requestBefore&&g.requestBefore();this.inputMobileNo&&(d.inputMobileNo=this.inputMobileNo);d.type=a;d.securityId=b.node(this.options.uniqElement).parent(".J-securitycoreMain").attr("data-request");
d.rnd=Math.random();d.creditMobileIndex=this.riskCredibleMobile.element.value;d.validateProductName="risk_mobile_credit";b.request(g.ajaxUrl,d,{method:"JSONP",success:function(d){if(d.info.sent){try{window!=window.parent?b.client.storage.set("riskMobileCreditSendTime",(new Date).getTime()):b.client.storage.set("riskMobileCreditSendTime",-1)}catch(e){}f.sendSuccess(a)}else f.showError(d.info);g.requestAfter&&f.options.requestAfter(d)}})},showError:function(a){this.itemExp.html(a.errorMessage);this.container.removeClass("ui-form-item-success").addClass("ui-form-item-error")},
sendSuccess:function(a){a=a||this.options.defaultType;this.container.removeClass("ui-form-item-error").addClass("ui-form-item-success");this.updatePrompt(a,"prompt_send")}},a))}(window.light,alipay.security);
light.has("/alipay/security/riskCredibleMobile")||function(b){try{window==window.parent&&b.client.storage.set("riskCredibleMobileSendTime",-1)}catch(k){}var i=function(){this.init.apply(this,arguments);this.bind()};i.prototype={_cg:{item:"ui-form-item",itemSuccess:"ui-form-item-success",itemError:"ui-form-item-error",itemExp:"ui-form-explain"},init:function(a){a=this.opt=a;a.dataId=a.id+(new Date).getTime()+Math.floor(1E3*Math.random());b.node("[id="+a.id+"]:not([data-id]):first").attr("data-id",
a.dataId);this.opt.uniqElement=b.node("[data-id="+a.dataId+"]:first")[0];this.element=this.opt.uniqElement;this.container=b.node(this.element).parent("."+this._cg.item);this.counter=this.container.next(".ui-form-item-counter");this.validateBtn=this.container.find(".validate-btn");this.itemExp=this.container.find("."+this._cg.itemExp);this.preExp=this.itemExp.html()||"";this.expand=!1;this.opt.mobile?(this.opt.mobile.origin="credible",this.opt.mobile.credibleValidate=!1,this.opt.mobile.riskCredibleMobile=
this):b.log("Mobile did not start.")},bind:function(){var a=this;this.validateBtn.click(function(){a.validateBtn.hide();a.validateNum();a.counter.removeClass("fn-hide").removeClass(a._cg.itemError).addClass(a._cg.itemSuccess);a.counter.find("."+a._cg.itemExp).html(a.counter.find("input").attr("data-explain"));a.expand=!0});b.node(this.element).change(function(){a.validateBtn.show();a.counter.addClass("fn-hide");a.counter.find(".reSend-btn").removeClass("fn-hide");a.counter.find(".sms-btn").addClass("fn-hide");
a.expand=!1});b.node(this.element).focus(function(){a.showDefault()})},validateNum:function(){0===this.element.value.replace(/[^\x00-\xff]/g,"**").length?this.showError({msg:"\u8bf7\u8f93\u5165\u624b\u673a\u53f7\u7801\u3002"}):this.request()},request:function(){var a=this,h=b.trim(this.element.value),c={};if(window!=window.parent){var d=(new Date).getTime(),e=Number(b.client.storage.get("riskCredibleMobileSendTime")),f=b.client.storage.get("riskCredibleMobileNo");if(h==f&&0>d-e)return}c.creditMobileIndex=
h;c.validateProductName="risk_mobile_credit";c.securityId=b.node(this.opt.uniqElement).parent(".J-securitycoreMain").attr("data-request");b.request(this.opt.ajaxUrl,c,{method:"JSONP",success:function(c){if(c.info.sent)try{window!=window.parent?(b.client.storage.set("riskCredibleMobileSendTime",(new Date).getTime()),b.client.storage.set("riskCredibleMobileNo",h)):b.client.storage.set("riskCredibleMobileSendTime",-1)}catch(d){}else a.showError(c.info)}})},validateNumSuc:function(){},error:function(a){var a=
a.info,b="";5<=a.errorCount&&this.validateBtn.addClass("ui-checkcode-messagecode-disabled-btn").attr("disabled",!0);b=b||a.errorMessage;this.showError({code:a.errorCode,msg:b})},showError:function(a){a.msg=a.msg||a.errorMessage;a.msg&&(this.itemExp.html(a.msg),this.counter.find("."+this._cg.itemExp).html(a.msg),this.counter.addClass(this._cg.itemError).removeClass(this._cg.itemSuccess))},showDefault:function(){this.itemExp.html(this.preExp);this.container.removeClass(this._cg.itemError)}};b.register("/alipay/security/riskCredibleMobile",
window,i)}(window.light);