light.has("/alipay/security/page")||function(e,c,a){a.page={};a.page.processCertLink=function(b){if(b.length)try{if(window.frameElement)b.attr("data-href")&&b.attr("href",b.attr("data-href")),b.attr("target","_blank");else{i=0;for(l=b.length;i<l;i++){var f=b[i];if(!/isNewCtrl/.test(f.href)){var d=/\?(.*)/.test(f.href)?"&":"?";f.href=a.cdo.installed?f.href+(d+"isNewCtrl=true"):f.href+(d+"isNewCtrl=false")}e.page.ui.dialog({type:"page",trigger:f,width:612,content:f.href,autoShow:!1})}}}catch(h){b.attr("data-href")&&
b.attr("href",b.attr("data-href")),b.attr("target","_blank")}}}(window.light,light.node,alipay.security);
light.has("/alipay/security/core")||function(e,c,a){var b=function(){var f={form:null,loadingClass:"ui-form-status",validateUrl:"",reCheckUrl:"",beforeAjaxValidate:light.noop,afterAjaxValidate:light.noop,block:light.noop,reCheckSuccess:light.noop,stopSubmit:!1,validatedSuccess:null,beforeSubmit:null};if(e!=e.top&&"true"!=light.client.storage.get("overLimit"))try{light.client.storage.set("overLimit","false"),light.client.storage.set("blockReason",""),light.client.storage.set("overLimitedProduct","")}catch(d){}var h=
{bind:function(){e!=e.top&&"true"==light.client.storage.get("overLimit")&&this.overLimit(light.client.storage.get("blockReason"),light.client.storage.get("overLimitedProduct"));light.on(document,"click keyup",function(a){var b=0;27==a.which?b=1:a.target&&a.target.className&&-1!==a.target.className.indexOf("xbox-close-link")&&(b=1,a.cancel());b&&light.page.ui.closeDialog()});var a=function(a){a=light.node(a);a.val()||a.val(a.attr("placeholder")).addClass("ui-form-item-placeholder")};light.node(".J-securitycoreMain [placeholder]").each(function(){a(light.node(this))}).click(function(){var a=
light.node(this);a.val()==a.attr("placeholder")&&a.val("");a.removeClass("ui-form-item-placeholder")}).blur(function(){a(light.node(this))})},execute:function(){if(this.requestContext.stoped){var b=this,d=this.scProducts,f=light.node(".J-securitycoreMain",this.form).attr("data-status");d.length&&!this.inited&&a.core.init.call(this,this.options);this.requestContext.stoped=!1;this._q.clear();light.each(this._products,function(a,d){b._q.add(function(a){d.execute(a,b.requestContext)})});this._q.add(function(a){d.length?
b.barcodeOnly||b.riskOneKeyConfirmOnly?(b.options.validatedSuccess&&b.options.validatedSuccess(),a()):b.ajaxValidate(a,b.requestContext.params):"true"!=f&&a()});this._q.add(function(){b.formSuccess()});this._q.invoke();this.requestContext.stoped=!0}},ajaxValidate:function(a,b){if(this.validated)a();else{light.log("Begin ajax validat.");this.showLoadingBar();this.options.beforeAjaxValidate();var d=this;light.packetRequest(this.options.validateUrl,{securityId:light.node(".J-securitycoreMain",this.form).attr("data-request")},
b,{success:function(b){d.ajaxValidateSucc(a,b)},abort:function(a){d.ajaxValidateFail(a)}})}},overLimit:function(a,b){for(var d=a.split(","),f=0,h=d.length;f<h;f++)if("risk_validate_over_limit_times"==d[f]){var c=light.node(".J-securitycoreMain"),e=light.node("."+b+"-blockReason");0>=e.length&&(e=light.node("#blockReason"));c.children().hide();e.appendTo(c);if(c.parent("form").length){var j=c.parent("form");j.children().hide();j[0].insertBefore(c[0],j[0].firstChild);c.show()}c[0].insertBefore(e[0],
c[0].firstChild);e.show();c.show();light.node(".loading-text").hide();try{light.client.storage.set("overLimit","true"),light.client.storage.set("blockReason",a),light.client.storage.set("overLimitedProduct",b)}catch(s){}}},updateRdsToken:function(a){a&&a.info&&a.info.rdsToken&&(window.form_tk=a.info.rdsToken,UA_Opt.setToken(window.form_tk),UA_Opt.reload())},ajaxValidateSucc:function(a,d){var f=d.info,c=!0,h=null;if(d.blockReason){c="";if(f.product&&f.product.length)for(var e=0,m=f.product.length;e<
m;e++){var j=f.product[e];if(j.overLimited){c=j.name;break}}this.overLimit(d.blockReason,c)}else{try{light.client.storage.set("overLimit","false"),light.client.storage.set("overLimitedProduct","")}catch(s){}if(f.product&&f.product.length){e=0;for(m=f.product.length;e<m;e++){var j=f.product[e],o=b.ajaxParams[j.name];0<="ukey,thirdkey,cert".indexOf(o)&&!j.validated?h=j:"checkCode"==o?this._products[o].afterValidate(j.validated,j.message):this._products[o].afterValidate(j.validated,j.message,j.validated);
!j.validated&&(c=j.validated);light.log("%s validate %s",o,j.validated)}h&&this._products[h.name].afterValidate(h.validated,h.message,h.validated);c?(this.validated=!0,a()):this.stopSubmit(d)}else f.exception&&this.ajaxValidateFail(f.exception);this.validated&&this.options.validatedSuccess&&this.options.validatedSuccess()}this.updateRdsToken(d)},ajaxValidateFail:function(a){this.stopSubmit();this._products.edit?this._products.edit.afterValidate(!1,a):alert(a)},stopSubmit:function(a){this.requestContext.stoped=
!0;this.hideLoadingBar();this.options.afterAjaxValidate(a)},showLoadingBar:function(){this.loading&&this.loading.removeClass("fn-hide")},hideLoadingBar:function(){this.loading&&this.loading.addClass("fn-hide")},formSuccess:function(){this.options.beforeSubmit&&this.options.beforeSubmit();var a=window.light.page.products,b,d;for(d in a)b=a[d],"rsainput"==b.__type.Name&&(b.element.value="");this.options.stopSubmit||this.options.form.submit()},getStatus:function(){return window.um&&window.um.getStatus()}};
return{init:function(d){if(!(this instanceof b.init))return new b.init(d);light.extend(this,h);this.inited=!1;this._products={};this.requestContext={stoped:!0,params:{}};this._q=new light.queue;this.validated=!1;var c=this;this.options=d=light.extend({},f,d);this.form=d.form;var e=light.node(".J-securitycoreMain",this.form),n=e.attr("data-status"),e=e.attr("data-server");d.reCheckUrl=d.reCheckUrl?d.reCheckUrl:e+"/securityAjaxCertRecheck.json";d.validateUrl=d.validateUrl?d.validateUrl:e+"/securityAjaxValidate.json";
this.loading=light.node("."+d.loadingClass,d.form);this.scProducts=light.page.scProducts;if("true"==n)return a.core.block(d.reCheckUrl,d.reCheckSuccess,d.preventDefaultReCheckSuccess),d.block(),this;if(1==this.scProducts.length&&"barcode"==this.scProducts[0].__type.Name){if((this.barcodeOnly=!0)&&this.options.barcodeAutoSubmit)this.scProducts[0].onConfirm(function(){c.options.validatedSuccess&&c.options.validatedSuccess();c.formSuccess()})}else this.barcodeOnly=!1;1==this.scProducts.length&&"riskOneKeyConfirm"==
this.scProducts[0].__type.Name?(this.riskOneKeyConfirmOnly=!0,this.scProducts[0].onConfirm(function(){c.options.validatedSuccess&&c.options.validatedSuccess();c.formSuccess()})):this.riskOneKeyConfirmOnly=!1;light.each(this.scProducts,function(a,d){var f=b.prodConfig[d.__type.Name],h=this.options?this.options[f]:null;if(!h||!h.skipChecking)c._products[f]=b.base.create(b[f],d,h)});a.core.visualTip();h.bind();light.page.scProducts=[];this.inited=!0;return this}}}();light.register("alipay/security/core",
e,b)}(window,light.page.ui.dialog,alipay.security);
(function(e,c,a){a.prodConfig={"control.edit":"edit","control.npedit":"edit",rsainput:"edit",noedit:"edit",mobile:"mobile",ctuMobile:"ctuMobile",otp:"otp",cert:"cert",ukey:"ukey",thirdkey:"thirdkey",riskMobileBank:"riskMobileBank",riskMobileAccount:"riskMobileAccount",riskMobileCredit:"riskMobileCredit",riskCertificate:"riskCertificate",riskSecurityQa:"riskSecurityQa",riskExpressPrivacy:"riskExpressPrivacy",riskOneKeyConfirm:"riskOneKeyConfirm",riskSudoku:"riskSudoku",checkCode:"checkCode",rds:"rds",
barcode:"barcode"};a.ajaxParams={cert:"cert",ukey:"ukey",thirdkey:"thirdkey",payment_password:"edit",query_password:"edit",operation_password:"edit",otp:"otp",mobileotp:"otp",ctu_mobile:"ctuMobile",mobile_replace:"mobile",mobile_free:"mobile",mobile_pay:"mobile",mobile_bank:"mobile",mobile_special_bank:"mobile",risk_mobile_bank:"riskMobileBank",risk_mobile_account:"riskMobileAccount",risk_mobile_credit:"riskMobileCredit",risk_certificate:"riskCertificate",risk_security_qa:"riskSecurityQa",risk_express_privacy:"riskExpressPrivacy",
risk_onekey_confirm:"riskOneKeyConfirm",risk_mobile_account_sudoku:"riskSudoku",risk_mobile_bank_sudoku:"riskSudoku",check_code:"checkCode",rds:"rds",barcode:"barcode"}})(window,light.page.ui.dialog,alipay.security.core);
light.has("/alipay/security/core/recheck")||function(e,c,a){a.core.certCheck=function(b,f){var d=b.data,c="",k=function(){a.create(a.pta).render(function(){for(var a=d.attr("data-sn").split("&"),b=0,e=a.length;b<e;b++)if(c=this.sign(d.attr("data-random"),a[b],d.attr("data-issuer"))){f({signedData:c});return}f({signedData:""})})},g=function(){a.create(a.pta).render(function(){(c=this.sign(d.attr("data-random"),d.attr("data-sn"),d.attr("data-issuer"),"",d.attr("data-subject")))?f({signedData:c}):f()})},
p=function(){a.cdo.handlers["*"]=a.cdo.handlers[12004]=function(){f()};a.create(a.cdo).render(function(){this.execute(e.unescapeHTML(d.attr("data-cmd")),function(a){f({certCmdOutput:a.rawData})})})};"cert"==b.type?a.cdo.installed?function(){a.cdo.handlers["*"]=a.cdo.handlers[12004]=function(){f({certCmdOutput:""})};a.create(a.cdo).render(function(){this.execute(e.unescapeHTML(d.attr("data-cmd")),function(a){f({certCmdOutput:a.rawData})})})}():a.pta.installed?k():f({}):"ukey"==b.type?a.cdo.installed&&
e.unescapeHTML(d.attr("data-cmd"))?p():a.pta.installed&&e.client.info.engine.trident&&g():"thirdkey"==b.type&&e.client.info.engine.trident&&a.pta.installed&&g()};a.core.recheck=function(b){var f=function(a){b.element.addClass("fn-hide");b.element.item(a).removeClass("fn-hide")},d=function(){g&&clearTimeout(g);f(4);a.core.certCheck(b,function(a){"undefined"!=typeof a?(f(3),e.packetRequest(b.url,{securityId:c(".J-securitycoreMain").attr("data-request")},a,{success:k,abort:h})):h()})},h=function(){g&&
clearTimeout(g);g=setTimeout(function(){f(1);if("ukey"==b.type||"thirdkey"==b.type)g=setTimeout(d,5E3)},800)},k=function(d){var d=d.info,f=d.message;g&&clearTimeout(g);e.log(f);if("block"==f||"success"==f){if("block"==f||"success"==f&&!b.preventDefaultReCheckSuccess){var k=document.createElement("div"),q=c(".J-securitycoreMain"),m=c(".J-securitycoreTip");k.innerHTML=d.html;q.parent()[0].insertBefore(c(".J-securitycoreMain",k)[0],q[0]);m.length&&m.parent()[0].insertBefore(c(".J-securitycoreTip",k)[0],
m[0]);q.del();m.length&&m.del();e.each(c("script",c(".J-securitycoreMain")),function(){eval(this.text)})}"block"==f?a.core.block(b.url,b.callback):"success"==f&&(c(".ui-securitycore").removeClass("fn-hide"),a.core.visualTip(),b.callback&&b.callback())}else h()},g=setTimeout(d,100);c(".J_reCheck").click(function(a){a.cancel();d(a)});b.element.item(1).mouseover(function(a){a&&g&&clearTimeout(g)}).mouseout(function(){g=setTimeout(d,4E3)})}}(window.light,light.node,alipay.security);
light.has("/alipay/security/core/block")||function(e,c,a){var b=function(a){return e.get(a)},f=function(a){for(var b=0,d=a.length;b<d;b++){var f=a[b];if(f.rule(f.id)){c("#"+f.id).removeClass("fn-hide");f.callback&&f.callback(c("#"+f.id));"cashier"==k&&(f.seed+="_cashier");e.track(f.seed);break}}};certElems=[{id:"J_certOs",rule:b,seed:"AQ_CA_OSnotSupport"},{id:"J_certNoPta",rule:function(){return"true"!==e.node("#J-cert-section").attr("data-alternative")&&!a.pta.installed&&!a.cdo.installed},seed:"AQ_CA_noPta"},
{id:"J_certNotUse",rule:b,seed:"AQ_CA_no"},{id:"J_certChecking",rule:b,seed:"AQ_CA_no",callback:function(b){b={type:"cert",element:c("#J_certNo, #J_certNotFound, #J_certFound, #J_certValidating, #J_certChecking"),data:b,url:d,callback:h,preventDefaultReCheckSuccess:g};a.core.recheck(b)}},{id:"J_certOverdue",rule:b,seed:"AQ_CA_update"},{id:"J_certException",rule:b,seed:""},{id:"J_publicException",rule:b,seed:""}];ukeyElems=[{id:"J_ukeyOs",rule:b,seed:"AQ_KEY_OSnotSupport"},{id:"J_ukeyBrowser",rule:b,
seed:"AQ_KEY_notSupport"},{id:"J_ukeyNoPta",rule:function(){return!a.cdo.installed&&(!a.pta.installed||!a.hwpta.installed)},seed:"AQ_KEY_noPta"},{id:"J_ukeyInActive",rule:b,seed:"AQ_KEY_inActive"},{id:"J_ukeyChecking",rule:b,seed:"AQ_KEY_noKey",callback:function(b){b={type:"ukey",element:c("#J_ukeyNoKey, #J_ukeyNotFound, #J_ukeyFound, #J_ukeyValidating, #J_ukeyChecking"),data:b,url:d,callback:h,preventDefaultReCheckSuccess:g};a.core.recheck(b)}},{id:"J_ukeyInLost",rule:b,seed:"AQ_KEY_cancel"},{id:"J_ukeyOverdue",
rule:b,seed:"AQ_KEY_update"},{id:"J_ukeyException",rule:b,seed:""},{id:"J_publicException",rule:b,seed:""}];thirdkeyElems=[{id:"J_thirdkeyOs",rule:b,seed:"AQ_UKEY_OSnotSupport"},{id:"J_thirdkeyBrowser",rule:b,seed:"AQ_UKEY_notSupport"},{id:"J_thirdkeyNoPta",rule:function(){return!a.pta.installed},seed:"AQ_UKEY_noPta"},{id:"J_thirdkeyChecking",rule:b,seed:"AQ_UKEY_noKey",callback:function(b){b={type:"thirdkey",element:c("#J_thirdkeyNo, #J_thirdkeyNotFound, #J_thirdkeyFound, #J_thirdkeyValidating, #J_thirdkeyChecking"),
data:b,url:d,callback:h,preventDefaultReCheckSuccess:g};a.core.recheck(b)}},{id:"J_thirdkeyOverdue",rule:b,seed:"AQ_UKEY_update"},{id:"J_thirdkeyLogoff",rule:b,seed:"AQ_UKEY_cancel"},{id:"J_thirdkeyException",rule:b,seed:""},{id:"J_publicException",rule:b,seed:""}];var d,h,k,g;a.core.block=function(b,n,r){d=b;h=n;g=r;k=c(".J-securitycoreMain").attr("data-system");c("#J_scCheck").addClass("fn-hide");c(".cert-section").length?f(certElems):c(".ukey-section").length?(f(ukeyElems),c(".ukeyDownLink").attr("href",
a.cdo.info.downloadUrl)):c(".thirdkey-section").length&&(f(thirdkeyElems),c(".thirdkeyDownLink").attr("href",a.pta.info.downloadUrl));c(".downLinkFirst").click(function(){var a=c(this).parent(".ui-tip");a.addClass("fn-hide");c("#"+a.attr("id")+"Clicked").removeClass("fn-hide")});a.page.processCertLink(c(".linkInXbox"));new e.pop({targets:c(".showCertTip"),className:"ui-securitycore",width:340,direction:"down"});"cashier"==k&&c(".J-securitycoreMain [seed]").each(function(a,b){var b=c(b),d=b.attr("seed");
b.attr("seed",d+"_cashier")})}}(window.light,light.node,alipay.security);
light.has("/alipay/security/core/visualTip")||function(e,c,a){a.core.visualTip=function(){setTimeout(function(){if(light.node(".J-securitycoreTip").length){var b=light.node(".J-securitycoreTip"),f=light.node(".J-checkResult",b),d=f.html(),f="ui-form-item-"+(f.attr("data-status")||"success");light.node(".ui-form-item",b).removeClass("ui-form-item-loading").addClass(f);if(light.node(".J-security-cert-is-not-use").length&&!a.pta.installed&&!a.cdo.installed)var d=a.securityCenterServer+"/cert/downLoadCtrl.htm",
f=a.securityCenterServer+"/cert/manage.htm",h=b.attr("data-link-in-xbox"),d='\u5c1a\u672a\u5b89\u88c5\u6570\u5b57\u8bc1\u4e66\u63a7\u4ef6\uff0c\u60a8\u53ef\u4ee5\u4f7f\u7528\u5b9d\u4ee4\u8fdb\u884c\u6821\u9a8c \u6216 <a href="'+(h?d:f)+'" class="'+h+'" seed="AQ_CA_noPtaClick" target="_blank" data-href="'+f+'">\u5b89\u88c5\u6570\u5b57\u8bc1\u4e66\u63a7\u4ef6</a>\u3002';light.node(".ui-form-explain",b).html(d);a.page.processCertLink(c(".linkInXbox"))}},2E3)}}(window.light,light.node,alipay.security);
light.has("/alipay/security/core/base")||function(e,c,a){var b,f=[];b=a.base=function(a){if(a!==f)throw"invalid constructor, use create() instead.";};b.defaults={errorMsg:"",rule:function(a){return!light.trim(a).length?!1:!0},itemClass:"ui-form-item",notifyClass:"ui-form-explain",errorClass:"ui-form-item-error",successClass:"ui-form-item-success",focusClass:"ui-form-item-focus"};b.create=function(a,c,e){if(!a)throw"this security product not exist";var g=new a(f);g.__type=a;a.defaults=light.extend({},
b.defaults,a.defaults);g.options=light.extend({},a.defaults,e);g.product=c;g.postInit();return g};b.prototype={postInit:function(){this.element=light.node("#"+this.product.options.id);this.parent=this.element.parent("."+this.options.itemClass);this.msg=this.parent.find("."+this.options.notifyClass);this.defaultMsg=this.element.attr("data-explain")||"";this.bind();light.track("sc_"+this.product.__type.Name)},bind:function(){var a=this;light.on(this.product.options.id,"focus",function(){a.afterValidate(!0)})},
execute:function(a,b){this.getValue(b);this.validate()?a():b.stoped=!0},getValue:function(a){var b=this;this.product.render(function(){b.value=this.getValue();a.params[b.options.paramName]=b.value})},validate:function(){var a=this.options.rule;this.value==light.node(this.product.element).attr("placeholder")&&(this.value="");this.isValid=light.isFunction(a)?a(this.value):a.test(this.value);this.afterValidate(this.isValid);return this.isValid},lock:function(a){a&&light.node(this.product.element).addClass("ui-input-unwrite").attr("disabled",
!0)},afterValidate:function(a,b,f){var c=this.options,b=b||c.errorMsg;this.lock(f);a?(this.parent.removeClass(c.successClass).removeClass(c.errorClass),this.msg.html(this.defaultMsg)):(this.parent.removeClass(c.successClass).addClass(c.errorClass),this.msg.html(light.trim(b)))}}}(window,light.page.ui.dialog,alipay.security.core);
light.has("/alipay/security/core/edit")||function(e,c){var a;c.edit=a=light.deriveFrom(c.base,{postInit:function(){this.parent=light.node("#"+this.product.options.hidnId).parent("."+this.options.itemClass);this.msg=this.parent.find("."+this.options.notifyClass);this.defaultMsg=this.msg.html();this.bind();light.track("sc_"+this.product.__type.Name)},getValue:light.noop,execute:function(a,f){var d=this,c=this.parent.find("input[name=J_aliedit_key_hidn]")[0].value,e=this.parent.find("input[name=J_aliedit_uid_hidn]")[0].value,
g=this.parent.find("input[name=J_aliedit_using]")[0].value,p=this.parent.find("input[name=J_aliedit_prod_type]")[0].value;if("true"==g&&!alipay.security.edit.installed&&!alipay.security.npedit.installed)alipay.security.edit.detect(),f.stoped=!0;else this.product.onready(function(){light.get(c).value=d.value=this.getPassword();"true"==g&&g&&d.parent.find("input[name=_seaside_gogo_]").val(this.getCi1());if(d.validate()){var n={J_aliedit_key_hidn:c,J_aliedit_uid_hidn:e,J_aliedit_using:g,_seaside_gogo_:"true"==
g?this.getCi1():""};n[c]=d.value;n[e]=light.get(e).value;d.ajaxData=light.extend({},n);d.ajaxData[p]=light.extend({},n);f.params=light.extend(f.params,d.ajaxData);a()}f.stoped=!0})},lock:light.noop,afterValidate:function(a,f,d){this.parent.find("input[name=J_aliedit_key_hidn]");var c=this.parent.find("input[name=J_aliedit_prod_type]")[0].value,e=this.options,f=f||e.errorMsg[c];this.lock(d);a?(this.parent.removeClass(e.successClass).removeClass(e.errorClass),this.msg.html(this.defaultMsg)):(this.parent.removeClass(e.successClass).addClass(e.errorClass),
this.msg.html(light.trim(f)))}});a.defaults={errorMsg:{payment_password:"\u8bf7\u586b\u5199\u652f\u4ed8\u5bc6\u7801\u3002",query_password:"\u8bf7\u586b\u5199\u767b\u5f55\u5bc6\u7801\u3002",operation_password:"\u8bf7\u586b\u5199\u64cd\u4f5c\u5bc6\u7801\u3002"}}}(window,alipay.security.core);
light.has("/alipay/security/core/mobile")||function(e,c){var a=light.deriveFrom(c.base,{execute:function(a,f){if(this.product.origin&&"credible"==this.product.origin&&!this.product.credibleValidate){var d=this.product.credibleMobile;d.validateNum.call(d);f.stoped=!0}else this.getValue(f),this.validate()?a():f.stoped=!0},getValue:function(a){var f=this;this.product.render(function(){f.value=this.getValue();a.params[f.options.paramName]=f.value;a.params.mobileAckCode=f.value.mobileAckCode})}});a.defaults=
{errorMsg:"\u8bf7\u8f93\u51656\u4f4d\u6570\u5b57\u6821\u9a8c\u7801\u3002",rule:function(a){return/^\d{6}$/.test(a.mobileAckCode)}};c.mobile=a}(window,alipay.security.core);
light.has("/alipay/security/core/ctuMobile")||function(e,c){var a=light.deriveFrom(c.base,{execute:function(a,f){if(this.product.origin&&"credible"==this.product.origin&&!this.product.credibleValidate){var d=this.product.credibleMobile;d.validateNum.call(d);f.stoped=!0}else this.getValue(f),this.validate()?a():f.stoped=!0},getValue:function(a){var f=this;this.product.render(function(){f.value=this.getValue();a.params[f.options.paramName]=f.value;light.extend(a.params,f.value)})}});a.defaults={errorMsg:"\u8bf7\u8f93\u51656\u4f4d\u6570\u5b57\u6821\u9a8c\u7801\u3002",
rule:function(a){return/^\d{6}$/.test(a.mobileAckCode)},paramName:"ctu_mobile"};c.ctuMobile=a}(window,alipay.security.core);
light.has("/alipay/security/core/core/otp")||function(e){var c=light.deriveFrom(e.base,{getValue:function(a){var b=this;this.product.render(function(){b.value=this.getValue();a.params[b.options.paramName]=b.value;light.extend(a.params,b.value)})}});c.defaults={errorMsg:"\u8bf7\u8f93\u51656\u4f4d\u6570\u5b57\u6821\u9a8c\u7801\u3002",rule:function(a){return/^\d{6}$/.test(a.otpPassword)},paramName:"otp"};e.otp=c}(alipay.security.core);
light.has("/alipay/security/core/baseCert")||function(e,c,a,b){b.baseCert=e=light.deriveFrom(b.base,{bind:light.noop,getValue:light.noop,validate:light.noop,lock:light.noop,postInit:function(){var a=light.node(".J-securitycoreTip")[0]||light.node(".edit-section")[0]||light.node(".cert-section, .ukey-section, .thirdkey-section")[0];this.parent=light.node("."+this.options.itemClass,a);this.msg=this.parent.find("."+this.options.notifyClass);this.defaultMsg=(light.node(".J-checkResult",a)[0]||this.msg[0]).innerHTML;
light.track("sc_"+this.product.__type.Name)},showMessage:function(a,b){var c=this.options.label,e="";"ukey"==this.product.__type.Name&&(e=', <a href="'+this.product.exeDownloadUrl+'">\u7acb\u5373\u5b89\u88c5</a>');this.afterValidate(!1,{noPta:'\u60a8\u7684\u7535\u8111\u8fd8\u672a\u88c5\u63a7\u4ef6\uff0c\u8bf7<a href="'+this.product.__type.info.downloadUrl+'">\u7acb\u5373\u5b89\u88c5</a>\uff0c\u5b89\u88c5\u540e\u8bf7\u5237\u65b0\u6216\u91cd\u542f\u6d4f\u89c8\u5668\u3002',noKey:"\u6ca1\u6709\u68c0\u6d4b\u5230\u60a8\u7684"+
c+"\uff0c\u8bf7\u63d2\u5165\u540e\u91cd\u8bd5\u6216\u8bf7\u5c1d\u8bd5\u5b89\u88c5\u9a71\u52a8"+e,keyError:c+"\u51fa\u73b0\u5f02\u5e38"+(b?"\uff0c\u9519\u8bef\u4ee3\u7801\uff1a"+b.number:"")}[a])}});e.defaults={paramName:"signedData"};b.cert=light.deriveFrom(e,{execute:function(a,b){b.params[this.options.paramName]={singedData:"cert"};light.extend(b.params,{singedData:"cert"});a()}});b.cert.defaults=light.extend({},e.defaults,{label:"\u6570\u5b57\u8bc1\u4e66",paramName:"cert"});b.ukey=light.deriveFrom(e,
{execute:function(b,d){if(this.product.__type.installed){var c=this;this.product.onready(function(){if(a.cdo.installed&&this.cmd){var e=this;this.handlers["*"]=function(a){c.showMessage.call(c,"keyError",a);d.stoped=!0};this.handlers[12004]=function(a){c.showMessage.call(c,"noKey",a);d.stoped=!0};this.execute(light.unescapeHTML(this.cmd),function(a){c.certCmdOutput=a.rawData;d.stoped||(c.certCmdOutput?(light.get(e.id).value=c.certSign,d.params[c.options.paramName]={certCmdOutput:c.certCmdOutput},
light.extend(d.params,{certCmdOutput:c.certCmdOutput}),c.afterValidate(!0),b()):(c.showMessage("noKey"),d.stoped=!0))})}else this.handlers["*"]=function(a){c.showMessage.call(c,"keyError",a);d.stoped=!0},this.handlers["-2147483135"]=this.handlers["-2146434962"]=function(){d.stoped=!0},c.certSign=this.sign(this.src,this.certSn,this.issuerDn,"",this.subjectCN),d.stoped||(c.certSign?(light.get(this.id).value=c.certSign,d.params[c.options.paramName]={signedData:c.certSign},light.extend(d.params,{signedData:c.certSign}),
c.afterValidate(!0),b()):(c.showMessage("noKey"),d.stoped=!0))})}else this.showMessage("noPta"),d.stoped=!0}});b.ukey.defaults=light.extend({},e.defaults,{label:"\u652f\u4ed8\u76fe",paramName:"ukey"});b.thirdkey=light.deriveFrom(e,{execute:function(a,b){if(this.product.__type.installed){var c=this;this.product.onready(function(){this.handlers["*"]=function(a){c.showMessage.call(c,"keyError",a);b.stoped=!0};this.handlers["-2147483135"]=this.handlers["-2146434962"]=function(){b.stoped=!0};c.certSign=
this.sign(this.src,this.certSn,this.issuerDn,"",this.subjectCN);b.stoped||(c.certSign?(light.get(this.id).value=c.certSign,b.params[c.options.paramName]={signedData:c.certSign},light.extend(b.params,{signedData:c.certSign}),c.afterValidate(!0),a()):(c.showMessage("noKey"),b.stoped=!0))})}else this.showMessage("noPta"),b.stoped=!0}});b.thirdkey.defaults=light.extend({},e.defaults,{label:"U\u76fe",paramName:"thirdkey"})}(window,light.page.ui.dialog,alipay.security,alipay.security.core);
light.has("/alipay/security/core/riskMobileBank")||function(e,c){var a=light.deriveFrom(c.base,{execute:function(a,c){this.getValue(c);this.validate()?a():c.stoped=!0}});a.defaults={errorMsg:"\u8bf7\u8f93\u51656\u4f4d\u6570\u5b57\u6821\u9a8c\u7801\u3002",rule:function(a){return/\d{6}/.test(a.mobileAckCode)},paramName:"risk_mobile_bank"};c.riskMobileBank=a}(window,alipay.security.core);
light.has("/alipay/security/core/riskMobileAccount")||function(e,c){var a=light.deriveFrom(c.base,{execute:function(a,c){this.getValue(c);this.validate()?a():c.stoped=!0}});a.defaults={errorMsg:"\u8bf7\u8f93\u51656\u4f4d\u6570\u5b57\u6821\u9a8c\u7801\u3002",rule:function(a){return/\d{6}/.test(a.mobileAckCode)},paramName:"risk_mobile_account"};c.riskMobileAccount=a}(window,alipay.security.core);
light.has("/alipay/security/core/riskMobileCredit")||function(e,c){var a=light.deriveFrom(c.base,{execute:function(a,c){this.getValue(c);this.validate()?a():c.stoped=!0}});a.defaults={errorMsg:"\u8bf7\u8f93\u51656\u4f4d\u6570\u5b57\u6821\u9a8c\u7801\u3002",rule:function(a){return/\d{6}/.test(a.mobileAckCode)},paramName:"risk_mobile_credit"};c.riskMobileCredit=a}(window,alipay.security.core);
light.has("/alipay/security/core/core/riskCertificate")||function(e){var c=light.deriveFrom(e.base,{});c.defaults={errorMsg:"\u8bf7\u586b\u5199\u8bc1\u4ef6\u7684\u6700\u540e6\u4f4d\u3002",rule:function(a){return/^.{6}$/.test(a.inputCertificateNo)},paramName:"risk_certificate"};e.riskCertificate=c}(alipay.security.core);
light.has("/alipay/security/core/core/riskSecurityQa")||function(e){var c=light.deriveFrom(e.base,{});c.defaults={errorMsg:"\u8bf7\u586b\u5199\u7b54\u6848\u3002",rule:function(a){return/\S+/.test(a.securityAnswer)},paramName:"risk_security_qa"};e.riskSecurityQa=c}(alipay.security.core);
light.has("/alipay/security/core/riskExpressPrivacy")||function(e){var c;light.deriveFrom(e.base,{});e.baseRiskExpressPrivacy=c=light.deriveFrom(e.base,{errorMsg:"\u6b63\u786e\u8bf7\u586b\u5199\u94f6\u884c\u5361\u53f7\u3002",rule:function(a){return/\d{16,24}/.test(a)},paramName:"risk_express_privacy",validate:function(){var a=this.rule,b=light.node(this.element),c=b.attr("placeholder");this.value=b.val().replace(/\D/g,"");this.value==c&&(this.value="");this.isValid=light.isFunction(a)?a(this.value):
a.test(this.value);this.afterValidate(this.isValid,this.errorMsg);return this.isValid},execute:function(a,b){this.validate()||(b.stoped=!0);if(!b.stoped){var c=this;this.product.queryValue(function(d){if(d.message)c.afterValidate(false,d.message);else{b.params[c.paramName]=d;c.afterValidate(true);a()}})}}});e.riskExpressPrivacy=light.deriveFrom(c,{})}(alipay.security.core);
light.has("/alipay/security/core/core/riskSudoku")||function(e){var c=light.deriveFrom(e.base,{postInit:function(){var a=this;this.product.onready(function(){a.element=a.product.element;a.parent=a.element.parent("."+a.options.itemClass);a.msg=a.parent.find("."+a.options.notifyClass);a.defaultMsg=a.element.attr("data-explain")||"";a.bind()});light.track("sc_"+this.product.__type.Name)},getValue:function(a){var b=this;this.product.render(function(){b.value=this.getValue();var c=[],d=this.letters;light.each(b.value.split(""),
function(a,b){c.push(d[b])});a.params[this.options.paramName]={index:c}})},bind:function(){var a=this,b=light.node("table tr td a",this.product.keyboard);light.each(b,function(b,c){light.on(c,"click",function(b){b.cancel();a.afterValidate(!0)})})},afterValidate:function(a,b,c){var d=this.options,b=b||d.errorMsg,e=this.element.parent(".input-container");explain=e.find("."+this.options.notifyClass);this.lock(c);a?(e.removeClass(d.successClass).removeClass(d.errorClass),explain.html(this.defaultMsg)):
(e.removeClass(d.successClass).addClass(d.errorClass),explain.html(light.trim(b)))}});c.defaults={errorMsg:"\u8bf7\u70b9\u51fb\u5de6\u4fa7\u8f93\u5165\u6821\u9a8c\u7801\u3002",rule:function(a){return!!a}};e.riskSudoku=c}(alipay.security.core);
light.has("/alipay/security/core/core/riskOneKeyConfirm")||function(e){var c=light.deriveFrom(e.base,{postInit:function(){var a=this;this.product.onready(function(){a.element=a.product.element;a.parent=a.element.parent();a.msg=a.parent.find("."+a.options.notifyClass);a.defaultMsg=a.element.attr("data-explain")||"";a.bind()});light.track("sc_"+this.product.__type.Name)},getValue:function(){var a=this;this.product.render(function(){a.value=this.getValue()})}});c.defaults={errorMsg:"\u8bf7\u5148\u5728\u652f\u4ed8\u5b9d\u94b1\u5305\u786e\u8ba4\u540e\u518d\u63d0\u4ea4\u3002",
rule:function(a){return a},paramName:"risk-onekey-confirm"};e.riskOneKeyConfirm=c}(alipay.security.core);
light.has("/alipay/security/core/core/checkCode")||function(e){var c=light.deriveFrom(e.base,{getValue:function(a){var b=this;this.product.render(function(){b.value=this.getValue();a.params[b.options.paramName]=b.value;light.extend(a.params,b.value)})}});c.defaults={errorMsg:"\u8bf7\u6b63\u786e\u586b\u5199\u6821\u9a8c\u7801\u3002",rule:function(a){return/^[a-zA-Z0-9]{4}$/.test(a.check_code)},paramName:"checkcode"};e.checkCode=c}(alipay.security.core);
light.has("/alipay/security/core/core/rds")||function(e){var c=light.deriveFrom(e.base,{afterValidate:function(){}});c.defaults={paramName:"rds",rule:function(){return!0}};e.rds=c}(alipay.security.core);
light.has("/alipay/security/core/core/barcode")||function(e){var c=light.deriveFrom(e.base,{postInit:function(){var a=this;this.product.onready(function(){a.element=a.product.element;a.parent=a.element.parent("."+a.options.itemClass);a.msg=a.parent.find("."+a.options.notifyClass);a.defaultMsg=a.element.attr("data-explain")||"";a.bind()});light.track("sc_"+this.product.__type.Name)},getValue:function(){var a=this;this.product.render(function(){a.value=this.getValue()})}});c.defaults={errorMsg:"\u8bf7\u626b\u63cf\u4e8c\u7ef4\u7801\u540e\uff0c\u518d\u63d0\u4ea4\u3002",
rule:function(a){return a},paramName:"barcode"};e.barcode=c}(alipay.security.core);