/*
 <a href="http://kjur.github.io/jsrsasign/license/">MIT License</a>
*/
light.has("/security/edit")||function(k,e){var i=light.client.info,p=alipay.security.downloadServer,n=alipay.security.securityCenterServer,x=function(){var e="windows"==i.os.name?"Alipay security control":"macos"==i.os.name?"Aliedit Plug-In":"linux"==i.os.name?"Aliedit":"",k="";if("windows"==i.os.name)k=p+"/sec/edit/aliedit.exe";else if("macos"==i.os.name)"safari"==i.browser.name?5<=navigator.userAgent.toLowerCase().match(/version\/(\d+\.\d+)/)[1]&&(k=p+"/aliedit/wkaliedit/1002/wkaliedit.dmg"):k=
p+"/aliedit/wkaliedit/1002/wkaliedit.dmg";else if("linux"==i.os.name&&("firefox"==i.browser.name||"chrome"==i.browser.name||"opera"==i.browser.name))k=p+"/alipaysc/linux/aliedit/1.0.3.20/aliedit.tar.gz";e={activex:"Aliedit.EditCtrl",plugin:e,classId:"488A4255-3236-44B3-8F27-FA1AECAA8844",type:"application/aliedit",version:"2.4.0.1",editSrc:k,cssSrc:(light.debug?"http://assets.dev.alipay.net":"https://a.alipayobjects.com")+("/al/alice.components.security-edit-1.4"+(light.debug?"-src":"")+".css"),installationPage:n+
"/sc/npedit/dialog.htm"};return{Name:"control.edit",info:e,template:i.engine.trident?'<object id="{id}" classid="clsid:{classId}" width="{width}" height="{height}" tabindex="{tabindex}"><param name="wmode" value="opaque" /><param name="cm5ts" value="{timestamp}" /><param name="cm5pk" value="{pk}" /><param name="PasswordMode" value="{passwordMode}" /><param name="CryptoMode" value="4" /></object>':'<object id="{id}" name="{name}" type="{type}" width="{width}" height="{height}" tabindex="{tabindex}"><param name="PasswordMode" value="{passwordMode}" /></object>',
available:!!e.editSrc,defaultMethod:"TextData"}}(),s=function(){e.cookie={days:365,domain:"."+light.baseDomain,path:"/"};var k=e.get("ac-stat"),n=null,r=!1,q=!1,p=function(){var n=this;"no"==k&&(e.set("ac-stat","success"),light.track("ac-success"));if(!i.engine.trident){var q=1;window.setTimeout(function(){var e=n.element.getElementsByTagName("param");e||window.setTimeout(arguments.callee,100);e[0].name=="PasswordMode"&&e[0].value=="0"&&function(){try{n.element.PasswordMode=0}catch(e){light.track(i.browser.name+
"-alieditBox-password-error")}if(n.element.PasswordMode!==0&&q<20){q++;window.setTimeout(arguments.callee,100)}}()},100)}};if(window.top!==window){var u=document.domain.split(".");1<u.length&&(document.domain=u[u.length-2]+"."+u[u.length-1])}var s=document,u=window,E={},A=x.info;try{if(window.top.document.body){s=window.top.document;do if(E=null!=u.frameElement?u.frameElement:{},/xbox/i.test(E.name)||/xbox/i.test(E.id))r=!0;while((u=u.parent)!=window.top&&!r)}}catch(K){q=!0}x.detect=function(){var e=
x.info;window.top.document.body&&(n=new light.dialog({targetFrame:s,iframeSrc:e.installationPage}));try{q||r?e.editSrc?location.href=e.editSrc:alert("\u60a8\u73b0\u5728\u6240\u7528\u7684\u6d4f\u89c8\u5668\uff0c\u6682\u4e0d\u652f\u6301\u5b89\u5168\u63a7\u4ef6\u3002"):n&&n.show()}catch(i){e.editSrc?location.href=e.editSrc:alert("\u60a8\u73b0\u5728\u6240\u7528\u7684\u6d4f\u89c8\u5668\uff0c\u6682\u4e0d\u652f\u6301\u5b89\u5168\u63a7\u4ef6\u3002")}return!1};var C=x._notInstalled=function(){if(!k||"success"==
k)e.set("ac-stat","no"),light.track("ac-no");var i=location.pathname;i&&/payment\/cashier\.htm/.test(i)&&light.track("ac-no-cashier");var n=this;(function(){n.options.container.innerHTML='<a href="'+A.installationPage+'" class="aliedit-install J_aliedit_xbox_link" seed="ac-link-tips">\u8bf7\u70b9\u6b64\u5b89\u88c5\u63a7\u4ef6</a>';var e=n.options.container.getElementsByTagName("a")[0];light.on(e,"click",function(e){e.cancel();x.detect()});setTimeout(function(){var e=light.node.build("div",{className:"edit-tips",
id:"edit-tips"});e.html('<a class="edit-tips-text" href="'+A.installationPage+'" seed="ac-link-intro">\u63a7\u4ef6\u53ef\u4fdd\u62a4\u60a8\u8f93\u5165\u4fe1\u606f\u7684\u5b89\u5168</a><div class="edit-tips-angle"></div>');e.appendTo(n.options.container);light.on(e[0],"click",function(e){e.cancel();x.detect()});var l=s.head||s.getElementsByTagName("head")[0]||s.documentElement;l.getElementsByTagName("link");var i=s.createElement("link");i.setAttribute("charset","utf-8");i.setAttribute("rel","stylesheet");
i.setAttribute("href",A.cssSrc);l.appendChild(i);light.on(document.body,"click",function(l){l=window.event||l;l=l.srcElement||l.target;e[0]&&void 0!=l.id&&(e[0].className="fn-hide")})},1500)})()};return{postInit:function(){if(this.__type.installed){var e=this;this.onready(function(){p.call(e)})}else C.call(this)},getInfo:function(e){if(!this.__type.installed)return"";var i="",l={ci1:"mac",ci2:"ipproxy",alieditVersion:"version",pw:"password"}[e];if(!this.element)return"";if("pw"!=e)try{i=this.element[e]();
if(/XOR_1_0{30}_/.test(i)||/(?:\d\.){3}\d/.test(i))return i;if("ci2"==e&&""===i)return"";light.track("ac-"+l+"-invalid",!0);return""}catch(o){return light.track("ac-"+l+"-interface-error",!0),""}else{i=this.element.TextData;if(/3DES_2_0{30}_/.test(i))return i;light.track("ac-"+l+"-invalid",!0);return""}},getCi1:function(){return this.getInfo("ci1")},getCi2:function(){return this.getInfo("ci2")},getVersion:function(){return this.getInfo("alieditVersion")},getPassword:function(){return this.getInfo("pw")}}}(),
x=k.edit=light.deriveFrom(k.base,s,x);x.defaults={};k.refreshStatus(k.edit)}(alipay.security,light.client.storage);
light.has("/security/npedit")||function(k,e){var i=light.client.info,p=alipay.security.downloadServer,n=alipay.security.securityCenterServer;npedit=function(){var e={activex:"npAliSecCtrl.SecCtrl",plugin:"Alipay Security Control 3",classId:"8EB7C6CB-2DA6-4ABE-B2EA-EAC5A372E757",type:"application/x-alisecctrl-plugin",version:"2.4.0.1",editSrc:p+"/sec/edit/aliedit.exe",cssSrc:(light.debug?"http://assets.dev.alipay.net":"https://a.alipayobjects.com")+("/al/alice.components.security-edit-1.4"+(light.debug?
"-src":"")+".css"),installationPage:n+"/sc/npedit/dialog.htm"};return{Name:"control.npedit",info:e,template:i.engine.trident?'<object id="{id}" name="{name}" classid="clsid:{classId}" width="{width}" height="{height}" tabindex="{tabindex}"><param name="prop" value="{prop}"></object>':'<object id="{id}" name="{name}" type="{type}" width="{width}" height="{height}" prop="{prop}" tabindex="{tabindex}" handler="{handler}"></object>',available:e.editSrc?!0:!1,minVersion:"1.0.0.1",defaultMethod:"GetMiscInfo"}}();
members=function(){e.cookie={days:365,domain:"."+light.baseDomain,path:"/"};var i=e.get("ac-stat"),k=function(){"no"==i&&(e.set("ac-stat","success"),light.track("ac-success"));try{var k=this.element.GetMiscInfo("2",0).match(/\d+/)[0]}catch(n){k=0,light.track("npedit-failure-detection-error",!0)}if(0<k&&1E3>k){light.track("BIZ_CODEBASE_ERR"+k,!0);var r=light.node.build("div",{className:"edit-tips-two-lines",id:"aliedit-tips"});r.html('<div class="edit-tips-text">\u68c0\u6d4b\u4e0d\u5230\u5b89\u5168\u63a7\u4ef6\uff0c\u6682\u4e0d\u80fd\u8f93\u5165</div><div class="edit-tips-angle"></div>');
r.appendTo(this.options.container);r=document.head||document.getElementsByTagName("head")[0]||document.documentElement;r.getElementsByTagName("link");var q=document.createElement("link");q.setAttribute("charset","utf-8");q.setAttribute("rel","stylesheet");q.setAttribute("href",this.__type.info.cssSrc);r.appendChild(q)}document.attachEvent&&this.element.attachEvent("onstatechange",function(e,i){if(e=="Error"&&i&&(k=i.match(/[^\d]*(\d+)?.*/)[1])){light.track("BIZ_CODEBASE_EVENT_ERR"+k,true);return false}})};
return{postInit:function(){if(this.__type.installed){var e=this;this.onready(function(){k.call(e)})}},getInfo:function(e,i,k){var n="",p={4:"mac",5:"ipproxy",Default:"password"}[i];if(!this.__type.installed||!this.element)return"";try{"GetMiscInfo"==e?n=this.element.GetMiscInfo(i,k):"GetEnInfo"==e&&(n=this.element.GetEnInfo(i,k))}catch(s){return light.track("npedit-"+p+"-interface-error",!0),""}if(3==i){if(1==n)return light.track("npedit-password-is-empty",!0),!1;if(0==n)return!0}if(344==n.length||
/XOR_1_0{30}_/.test(n))return n;if(5==i&&""===n)return"";light.track("npedit-"+p+"-invalid",!0);return""},getCi1:function(){return this.getInfo("GetMiscInfo","4",0)},getCi2:function(){return this.getInfo("GetMiscInfo","5",0)},getVersion:function(){return""},getPassword:function(){return!this.getInfo("GetMiscInfo","3",0)?"":this.getInfo("GetEnInfo","Default",0)}}}();npedit=k.npedit=light.deriveFrom(k.base,members,npedit);npedit.defaults={};k.refreshStatus(k.npedit);npedit.installed&&(npedit.installed=
k.edit.installed)}(alipay.security,light.client.storage);light.has("/security/noedit")||function(k){members={ready:!0,render:function(e){light.isFunction(e)&&this._readyList.push(e);(this.element=light.get(this.options.id))&&(this.element.value="");for(e=this._readyList;e.length;)e.shift().apply(this)},getPassword:function(){return this.element.value}};k.noedit=light.deriveFrom(k.base,members,{Name:"noedit"})}(alipay.security);light.has("/security/utils")||function(k){k.utils={}}(alipay.security);
(function(k){function e(a,c,b){null!=a&&("number"==typeof a?this.fromNumber(a,c,b):null==c&&"string"!=typeof a?this.fromString(a,256):this.fromString(a,c))}function i(){return new e(null)}function p(a,c,b,d,f,g){for(;0<=--g;){var h=c*this[a++]+b[d]+f,f=Math.floor(h/67108864);b[d++]=h&67108863}return f}function n(a,c,b,d,f,g){for(var h=c&32767,c=c>>15;0<=--g;){var j=this[a]&32767,e=this[a++]>>15,l=c*j+e*h,j=h*j+((l&32767)<<15)+b[d]+(f&1073741823),f=(j>>>30)+(l>>>15)+c*e+(f>>>30);b[d++]=j&1073741823}return f}
function x(a,c,b,d,f,g){for(var h=c&16383,c=c>>14;0<=--g;){var j=this[a]&16383,e=this[a++]>>14,l=c*j+e*h,j=h*j+((l&16383)<<14)+b[d]+f,f=(j>>28)+(l>>14)+c*e;b[d++]=j&268435455}return f}function s(a,c){var b=P[a.charCodeAt(c)];return null==b?-1:b}function z(a){var c=i();c.fromInt(a);return c}function J(a){var c=1,b;if(0!=(b=a>>>16))a=b,c+=16;if(0!=(b=a>>8))a=b,c+=8;if(0!=(b=a>>4))a=b,c+=4;if(0!=(b=a>>2))a=b,c+=2;0!=a>>1&&(c+=1);return c}function r(a){this.m=a}function q(a){this.m=a;this.mp=a.invDigit();
this.mpl=this.mp&32767;this.mph=this.mp>>15;this.um=(1<<a.DB-15)-1;this.mt2=2*a.t}function I(a,c){return a&c}function u(a,c){return a|c}function N(a,c){return a^c}function E(a,c){return a&~c}function A(){}function K(a){return a}function C(a){this.r2=i();this.q3=i();e.ONE.dlShiftTo(2*a.t,this.r2);this.mu=this.r2.divide(a);this.m=a}function H(){this.j=this.i=0;this.S=[]}function D(){}function l(a,c){return new e(a,c)}function o(){this.n=null;this.e=0;this.coeff=this.dmq1=this.dmp1=this.q=this.p=this.d=
null}function S(a,c){for(var b=[],d=0,f=a.length;d<f;d++){var g=a.charCodeAt(d);128>g?b.push(g):127<g&&2048>g?(b.push(g&63|128),b.push(g>>6|192)):(b.push(g&63|128),b.push(g>>6&63|128),b.push(g>>12|224))}f=c-a.length;if(0<f)for(d=0;d<f;d++)b.push(0);return b}function O(a){var c,b,d="";for(c=0;c+3<=a.length;c+=3)b=parseInt(a.substring(c,c+3),16),d+=L.charAt(b>>6)+L.charAt(b&63);c+1==a.length?(b=parseInt(a.substring(c,c+1),16),d+=L.charAt(b<<2)):c+2==a.length&&(b=parseInt(a.substring(c,c+2),16),d+=L.charAt(b>>
2)+L.charAt((b&3)<<4));for(;0<(d.length&3);)d+=V;return d}function X(a){var c="",b,d=0,f;for(b=0;b<a.length&&a.charAt(b)!=V;++b)v=L.indexOf(a.charAt(b)),0>v||(0==d?(c+=F.charAt(v>>2),f=v&3,d=1):1==d?(c+=F.charAt(f<<2|v>>4),f=v&15,d=2):2==d?(c+=F.charAt(f),c+=F.charAt(v>>2),f=v&3,d=3):(c+=F.charAt(f<<2|v>>4),c+=F.charAt(v&15),d=0));1==d&&(c+=F.charAt(f<<2));return c}var t;"Microsoft Internet Explorer"==navigator.appName?(e.prototype.am=n,t=30):"Netscape"!=navigator.appName?(e.prototype.am=p,t=26):
(e.prototype.am=x,t=28);e.prototype.DB=t;e.prototype.DM=(1<<t)-1;e.prototype.DV=1<<t;e.prototype.FV=Math.pow(2,52);e.prototype.F1=52-t;e.prototype.F2=2*t-52;var F="0123456789abcdefghijklmnopqrstuvwxyz",P=[],w;t=48;for(w=0;9>=w;++w)P[t++]=w;t=97;for(w=10;36>w;++w)P[t++]=w;t=65;for(w=10;36>w;++w)P[t++]=w;r.prototype.convert=function(a){return a.s<0||a.compareTo(this.m)>=0?a.mod(this.m):a};r.prototype.revert=function(a){return a};r.prototype.reduce=function(a){a.divRemTo(this.m,null,a)};r.prototype.mulTo=
function(a,c,b){a.multiplyTo(c,b);this.reduce(b)};r.prototype.sqrTo=function(a,c){a.squareTo(c);this.reduce(c)};q.prototype.convert=function(a){var c=i();a.abs().dlShiftTo(this.m.t,c);c.divRemTo(this.m,null,c);a.s<0&&c.compareTo(e.ZERO)>0&&this.m.subTo(c,c);return c};q.prototype.revert=function(a){var c=i();a.copyTo(c);this.reduce(c);return c};q.prototype.reduce=function(a){for(;a.t<=this.mt2;)a[a.t++]=0;for(var c=0;c<this.m.t;++c){var b=a[c]&32767,d=b*this.mpl+((b*this.mph+(a[c]>>15)*this.mpl&this.um)<<
15)&a.DM,b=c+this.m.t;for(a[b]=a[b]+this.m.am(0,d,a,c,0,this.m.t);a[b]>=a.DV;){a[b]=a[b]-a.DV;a[++b]++}}a.clamp();a.drShiftTo(this.m.t,a);a.compareTo(this.m)>=0&&a.subTo(this.m,a)};q.prototype.mulTo=function(a,c,b){a.multiplyTo(c,b);this.reduce(b)};q.prototype.sqrTo=function(a,c){a.squareTo(c);this.reduce(c)};e.prototype.copyTo=function(a){for(var c=this.t-1;c>=0;--c)a[c]=this[c];a.t=this.t;a.s=this.s};e.prototype.fromInt=function(a){this.t=1;this.s=a<0?-1:0;a>0?this[0]=a:a<-1?this[0]=a+DV:this.t=
0};e.prototype.fromString=function(a,c){var b;if(c==16)b=4;else if(c==8)b=3;else if(c==256)b=8;else if(c==2)b=1;else if(c==32)b=5;else if(c==4)b=2;else{this.fromRadix(a,c);return}this.s=this.t=0;for(var d=a.length,f=false,g=0;--d>=0;){var h=b==8?a[d]&255:s(a,d);if(h<0)a.charAt(d)=="-"&&(f=true);else{f=false;if(g==0)this[this.t++]=h;else if(g+b>this.DB){this[this.t-1]=this[this.t-1]|(h&(1<<this.DB-g)-1)<<g;this[this.t++]=h>>this.DB-g}else this[this.t-1]=this[this.t-1]|h<<g;g=g+b;g>=this.DB&&(g=g-this.DB)}}if(b==
8&&(a[0]&128)!=0){this.s=-1;g>0&&(this[this.t-1]=this[this.t-1]|(1<<this.DB-g)-1<<g)}this.clamp();f&&e.ZERO.subTo(this,this)};e.prototype.clamp=function(){for(var a=this.s&this.DM;this.t>0&&this[this.t-1]==a;)--this.t};e.prototype.dlShiftTo=function(a,c){var b;for(b=this.t-1;b>=0;--b)c[b+a]=this[b];for(b=a-1;b>=0;--b)c[b]=0;c.t=this.t+a;c.s=this.s};e.prototype.drShiftTo=function(a,c){for(var b=a;b<this.t;++b)c[b-a]=this[b];c.t=Math.max(this.t-a,0);c.s=this.s};e.prototype.lShiftTo=function(a,c){var b=
a%this.DB,d=this.DB-b,f=(1<<d)-1,g=Math.floor(a/this.DB),h=this.s<<b&this.DM,j;for(j=this.t-1;j>=0;--j){c[j+g+1]=this[j]>>d|h;h=(this[j]&f)<<b}for(j=g-1;j>=0;--j)c[j]=0;c[g]=h;c.t=this.t+g+1;c.s=this.s;c.clamp()};e.prototype.rShiftTo=function(a,c){c.s=this.s;var b=Math.floor(a/this.DB);if(b>=this.t)c.t=0;else{var d=a%this.DB,f=this.DB-d,g=(1<<d)-1;c[0]=this[b]>>d;for(var h=b+1;h<this.t;++h){c[h-b-1]=c[h-b-1]|(this[h]&g)<<f;c[h-b]=this[h]>>d}d>0&&(c[this.t-b-1]=c[this.t-b-1]|(this.s&g)<<f);c.t=this.t-
b;c.clamp()}};e.prototype.subTo=function(a,c){for(var b=0,d=0,f=Math.min(a.t,this.t);b<f;){d=d+(this[b]-a[b]);c[b++]=d&this.DM;d=d>>this.DB}if(a.t<this.t){for(d=d-a.s;b<this.t;){d=d+this[b];c[b++]=d&this.DM;d=d>>this.DB}d=d+this.s}else{for(d=d+this.s;b<a.t;){d=d-a[b];c[b++]=d&this.DM;d=d>>this.DB}d=d-a.s}c.s=d<0?-1:0;d<-1?c[b++]=this.DV+d:d>0&&(c[b++]=d);c.t=b;c.clamp()};e.prototype.multiplyTo=function(a,c){var b=this.abs(),d=a.abs(),f=b.t;for(c.t=f+d.t;--f>=0;)c[f]=0;for(f=0;f<d.t;++f)c[f+b.t]=b.am(0,
d[f],c,f,0,b.t);c.s=0;c.clamp();this.s!=a.s&&e.ZERO.subTo(c,c)};e.prototype.squareTo=function(a){for(var c=this.abs(),b=a.t=2*c.t;--b>=0;)a[b]=0;for(b=0;b<c.t-1;++b){var d=c.am(b,c[b],a,2*b,0,1);if((a[b+c.t]=a[b+c.t]+c.am(b+1,2*c[b],a,2*b+1,d,c.t-b-1))>=c.DV){a[b+c.t]=a[b+c.t]-c.DV;a[b+c.t+1]=1}}a.t>0&&(a[a.t-1]=a[a.t-1]+c.am(b,c[b],a,2*b,0,1));a.s=0;a.clamp()};e.prototype.divRemTo=function(a,c,b){var d=a.abs();if(!(d.t<=0)){var f=this.abs();if(f.t<d.t){c!=null&&c.fromInt(0);b!=null&&this.copyTo(b)}else{b==
null&&(b=i());var g=i(),h=this.s,a=a.s,j=this.DB-J(d[d.t-1]);if(j>0){d.lShiftTo(j,g);f.lShiftTo(j,b)}else{d.copyTo(g);f.copyTo(b)}d=g.t;f=g[d-1];if(f!=0){var l=f*(1<<this.F1)+(d>1?g[d-2]>>this.F2:0),k=this.FV/l,l=(1<<this.F1)/l,o=1<<this.F2,n=b.t,m=n-d,p=c==null?i():c;g.dlShiftTo(m,p);if(b.compareTo(p)>=0){b[b.t++]=1;b.subTo(p,b)}e.ONE.dlShiftTo(d,p);for(p.subTo(g,g);g.t<d;)g[g.t++]=0;for(;--m>=0;){var q=b[--n]==f?this.DM:Math.floor(b[n]*k+(b[n-1]+o)*l);if((b[n]=b[n]+g.am(0,q,b,m,0,d))<q){g.dlShiftTo(m,
p);for(b.subTo(p,b);b[n]<--q;)b.subTo(p,b)}}if(c!=null){b.drShiftTo(d,c);h!=a&&e.ZERO.subTo(c,c)}b.t=d;b.clamp();j>0&&b.rShiftTo(j,b);h<0&&e.ZERO.subTo(b,b)}}}};e.prototype.invDigit=function(){if(this.t<1)return 0;var a=this[0];if((a&1)==0)return 0;var c=a&3,c=c*(2-(a&15)*c)&15,c=c*(2-(a&255)*c)&255,c=c*(2-((a&65535)*c&65535))&65535,c=c*(2-a*c%this.DV)%this.DV;return c>0?this.DV-c:-c};e.prototype.isEven=function(){return(this.t>0?this[0]&1:this.s)==0};e.prototype.exp=function(a,c){if(a>4294967295||
a<1)return e.ONE;var b=i(),d=i(),f=c.convert(this),g=J(a)-1;for(f.copyTo(b);--g>=0;){c.sqrTo(b,d);if((a&1<<g)>0)c.mulTo(d,f,b);else var h=b,b=d,d=h}return c.revert(b)};e.prototype.toString=function(a){if(this.s<0)return"-"+this.negate().toString(a);if(a==16)a=4;else if(a==8)a=3;else if(a==2)a=1;else if(a==32)a=5;else if(a==4)a=2;else return this.toRadix(a);var c=(1<<a)-1,b,d=false,f="",g=this.t,h=this.DB-g*this.DB%a;if(g-- >0){if(h<this.DB&&(b=this[g]>>h)>0){d=true;f=F.charAt(b)}for(;g>=0;){if(h<
a){b=(this[g]&(1<<h)-1)<<a-h;b=b|this[--g]>>(h=h+(this.DB-a))}else{b=this[g]>>(h=h-a)&c;if(h<=0){h=h+this.DB;--g}}b>0&&(d=true);d&&(f=f+F.charAt(b))}}return d?f:"0"};e.prototype.negate=function(){var a=i();e.ZERO.subTo(this,a);return a};e.prototype.abs=function(){return this.s<0?this.negate():this};e.prototype.compareTo=function(a){var c=this.s-a.s;if(c!=0)return c;var b=this.t,c=b-a.t;if(c!=0)return this.s<0?-c:c;for(;--b>=0;)if((c=this[b]-a[b])!=0)return c;return 0};e.prototype.bitLength=function(){return this.t<=
0?0:this.DB*(this.t-1)+J(this[this.t-1]^this.s&this.DM)};e.prototype.mod=function(a){var c=i();this.abs().divRemTo(a,null,c);this.s<0&&c.compareTo(e.ZERO)>0&&a.subTo(c,c);return c};e.prototype.modPowInt=function(a,c){var b;b=a<256||c.isEven()?new r(c):new q(c);return this.exp(a,b)};e.ZERO=z(0);e.ONE=z(1);A.prototype.convert=K;A.prototype.revert=K;A.prototype.mulTo=function(a,c,b){a.multiplyTo(c,b)};A.prototype.sqrTo=function(a,c){a.squareTo(c)};C.prototype.convert=function(a){if(a.s<0||a.t>2*this.m.t)return a.mod(this.m);
if(a.compareTo(this.m)<0)return a;var c=i();a.copyTo(c);this.reduce(c);return c};C.prototype.revert=function(a){return a};C.prototype.reduce=function(a){a.drShiftTo(this.m.t-1,this.r2);if(a.t>this.m.t+1){a.t=this.m.t+1;a.clamp()}this.mu.multiplyUpperTo(this.r2,this.m.t+1,this.q3);for(this.m.multiplyLowerTo(this.q3,this.m.t+1,this.r2);a.compareTo(this.r2)<0;)a.dAddOffset(1,this.m.t+1);for(a.subTo(this.r2,a);a.compareTo(this.m)>=0;)a.subTo(this.m,a)};C.prototype.mulTo=function(a,c,b){a.multiplyTo(c,
b);this.reduce(b)};C.prototype.sqrTo=function(a,c){a.squareTo(c);this.reduce(c)};var y=[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541,547,557,563,569,571,577,587,593,599,601,607,
613,617,619,631,641,643,647,653,659,661,673,677,683,691,701,709,719,727,733,739,743,751,757,761,769,773,787,797,809,811,821,823,827,829,839,853,857,859,863,877,881,883,887,907,911,919,929,937,941,947,953,967,971,977,983,991,997],Y=67108864/y[y.length-1];e.prototype.chunkSize=function(a){return Math.floor(Math.LN2*this.DB/Math.log(a))};e.prototype.toRadix=function(a){a==null&&(a=10);if(this.signum()==0||a<2||a>36)return"0";var c=this.chunkSize(a),c=Math.pow(a,c),b=z(c),d=i(),f=i(),g="";for(this.divRemTo(b,
d,f);d.signum()>0;){g=(c+f.intValue()).toString(a).substr(1)+g;d.divRemTo(b,d,f)}return f.intValue().toString(a)+g};e.prototype.fromRadix=function(a,c){this.fromInt(0);c==null&&(c=10);for(var b=this.chunkSize(c),d=Math.pow(c,b),f=false,g=0,h=0,j=0;j<a.length;++j){var l=s(a,j);if(l<0)a.charAt(j)=="-"&&this.signum()==0&&(f=true);else{h=c*h+l;if(++g>=b){this.dMultiply(d);this.dAddOffset(h,0);h=g=0}}}if(g>0){this.dMultiply(Math.pow(c,g));this.dAddOffset(h,0)}f&&e.ZERO.subTo(this,this)};e.prototype.fromNumber=
function(a,c,b){if("number"==typeof c)if(a<2)this.fromInt(1);else{this.fromNumber(a,b);this.testBit(a-1)||this.bitwiseTo(e.ONE.shiftLeft(a-1),u,this);for(this.isEven()&&this.dAddOffset(1,0);!this.isProbablePrime(c);){this.dAddOffset(2,0);this.bitLength()>a&&this.subTo(e.ONE.shiftLeft(a-1),this)}}else{var b=[],d=a&7;b.length=(a>>3)+1;c.nextBytes(b);b[0]=d>0?b[0]&(1<<d)-1:0;this.fromString(b,256)}};e.prototype.bitwiseTo=function(a,c,b){var d,f,g=Math.min(a.t,this.t);for(d=0;d<g;++d)b[d]=c(this[d],a[d]);
if(a.t<this.t){f=a.s&this.DM;for(d=g;d<this.t;++d)b[d]=c(this[d],f);b.t=this.t}else{f=this.s&this.DM;for(d=g;d<a.t;++d)b[d]=c(f,a[d]);b.t=a.t}b.s=c(this.s,a.s);b.clamp()};e.prototype.changeBit=function(a,c){var b=e.ONE.shiftLeft(a);this.bitwiseTo(b,c,b);return b};e.prototype.addTo=function(a,c){for(var b=0,d=0,f=Math.min(a.t,this.t);b<f;){d=d+(this[b]+a[b]);c[b++]=d&this.DM;d=d>>this.DB}if(a.t<this.t){for(d=d+a.s;b<this.t;){d=d+this[b];c[b++]=d&this.DM;d=d>>this.DB}d=d+this.s}else{for(d=d+this.s;b<
a.t;){d=d+a[b];c[b++]=d&this.DM;d=d>>this.DB}d=d+a.s}c.s=d<0?-1:0;d>0?c[b++]=d:d<-1&&(c[b++]=this.DV+d);c.t=b;c.clamp()};e.prototype.dMultiply=function(a){this[this.t]=this.am(0,a-1,this,0,0,this.t);++this.t;this.clamp()};e.prototype.dAddOffset=function(a,c){if(a!=0){for(;this.t<=c;)this[this.t++]=0;for(this[c]=this[c]+a;this[c]>=this.DV;){this[c]=this[c]-this.DV;++c>=this.t&&(this[this.t++]=0);++this[c]}}};e.prototype.multiplyLowerTo=function(a,c,b){var d=Math.min(this.t+a.t,c);b.s=0;for(b.t=d;d>
0;)b[--d]=0;var f;for(f=b.t-this.t;d<f;++d)b[d+this.t]=this.am(0,a[d],b,d,0,this.t);for(f=Math.min(a.t,c);d<f;++d)this.am(0,a[d],b,d,0,c-d);b.clamp()};e.prototype.multiplyUpperTo=function(a,c,b){--c;var d=b.t=this.t+a.t-c;for(b.s=0;--d>=0;)b[d]=0;for(d=Math.max(c-this.t,0);d<a.t;++d)b[this.t+d-c]=this.am(c-d,a[d],b,0,0,this.t+d-c);b.clamp();b.drShiftTo(1,b)};e.prototype.modInt=function(a){if(a<=0)return 0;var c=this.DV%a,b=this.s<0?a-1:0;if(this.t>0)if(c==0)b=this[0]%a;else for(var d=this.t-1;d>=
0;--d)b=(c*b+this[d])%a;return b};e.prototype.millerRabin=function(a){var c=this.subtract(e.ONE),b=c.getLowestSetBit();if(b<=0)return false;var d=c.shiftRight(b),a=a+1>>1;if(a>y.length)a=y.length;for(var f=i(),g=0;g<a;++g){f.fromInt(y[Math.floor(Math.random()*y.length)]);var h=f.modPow(d,this);if(h.compareTo(e.ONE)!=0&&h.compareTo(c)!=0){for(var j=1;j++<b&&h.compareTo(c)!=0;){h=h.modPowInt(2,this);if(h.compareTo(e.ONE)==0)return false}if(h.compareTo(c)!=0)return false}}return true};e.prototype.clone=
function(){var a=i();this.copyTo(a);return a};e.prototype.intValue=function(){if(this.s<0){if(this.t==1)return this[0]-this.DV;if(this.t==0)return-1}else{if(this.t==1)return this[0];if(this.t==0)return 0}return(this[1]&(1<<32-this.DB)-1)<<this.DB|this[0]};e.prototype.byteValue=function(){return this.t==0?this.s:this[0]<<24>>24};e.prototype.shortValue=function(){return this.t==0?this.s:this[0]<<16>>16};e.prototype.signum=function(){return this.s<0?-1:this.t<=0||this.t==1&&this[0]<=0?0:1};e.prototype.toByteArray=
function(){var a=this.t,c=[];c[0]=this.s;var b=this.DB-a*this.DB%8,d,f=0;if(a-- >0){if(b<this.DB&&(d=this[a]>>b)!=(this.s&this.DM)>>b)c[f++]=d|this.s<<this.DB-b;for(;a>=0;){if(b<8){d=(this[a]&(1<<b)-1)<<8-b;d=d|this[--a]>>(b=b+(this.DB-8))}else{d=this[a]>>(b=b-8)&255;if(b<=0){b=b+this.DB;--a}}(d&128)!=0&&(d=d|-256);f==0&&(this.s&128)!=(d&128)&&++f;if(f>0||d!=this.s)c[f++]=d}}return c};e.prototype.equals=function(a){return this.compareTo(a)==0};e.prototype.min=function(a){return this.compareTo(a)<
0?this:a};e.prototype.max=function(a){return this.compareTo(a)>0?this:a};e.prototype.and=function(a){var c=i();this.bitwiseTo(a,I,c);return c};e.prototype.or=function(a){var c=i();this.bitwiseTo(a,u,c);return c};e.prototype.xor=function(a){var c=i();this.bitwiseTo(a,N,c);return c};e.prototype.andNot=function(a){var c=i();this.bitwiseTo(a,E,c);return c};e.prototype.not=function(){for(var a=i(),c=0;c<this.t;++c)a[c]=this.DM&~this[c];a.t=this.t;a.s=~this.s;return a};e.prototype.shiftLeft=function(a){var c=
i();a<0?this.rShiftTo(-a,c):this.lShiftTo(a,c);return c};e.prototype.shiftRight=function(a){var c=i();a<0?this.lShiftTo(-a,c):this.rShiftTo(a,c);return c};e.prototype.getLowestSetBit=function(){for(var a=0;a<this.t;++a)if(this[a]!=0){var c=a*this.DB;a=this[a];if(a==0)a=-1;else{var b=0;if((a&65535)==0){a=a>>16;b=b+16}if((a&255)==0){a=a>>8;b=b+8}if((a&15)==0){a=a>>4;b=b+4}if((a&3)==0){a=a>>2;b=b+2}(a&1)==0&&++b;a=b}return c+a}return this.s<0?this.t*this.DB:-1};e.prototype.bitCount=function(){for(var a=
0,c=this.s&this.DM,b=0;b<this.t;++b){for(var d=this[b]^c,f=0;d!=0;){d=d&d-1;++f}a=a+f}return a};e.prototype.testBit=function(a){var c=Math.floor(a/this.DB);return c>=this.t?this.s!=0:(this[c]&1<<a%this.DB)!=0};e.prototype.setBit=function(a){return this.changeBit(a,u)};e.prototype.clearBit=function(a){return this.changeBit(a,E)};e.prototype.flipBit=function(a){return this.changeBit(a,N)};e.prototype.add=function(a){var c=i();this.addTo(a,c);return c};e.prototype.subtract=function(a){var c=i();this.subTo(a,
c);return c};e.prototype.multiply=function(a){var c=i();this.multiplyTo(a,c);return c};e.prototype.divide=function(a){var c=i();this.divRemTo(a,c,null);return c};e.prototype.remainder=function(a){var c=i();this.divRemTo(a,null,c);return c};e.prototype.divideAndRemainder=function(a){var c=i(),b=i();this.divRemTo(a,c,b);return[c,b]};e.prototype.modPow=function(a,c){var b=a.bitLength(),d,f=z(1),g;if(b<=0)return f;d=b<18?1:b<48?3:b<144?4:b<768?5:6;g=b<8?new r(c):c.isEven()?new C(c):new q(c);var h=[],
j=3,e=d-1,l=(1<<d)-1;h[1]=g.convert(this);if(d>1){b=i();for(g.sqrTo(h[1],b);j<=l;){h[j]=i();g.mulTo(b,h[j-2],h[j]);j=j+2}}for(var k=a.t-1,o,n=true,m=i(),b=J(a[k])-1;k>=0;){if(b>=e)o=a[k]>>b-e&l;else{o=(a[k]&(1<<b+1)-1)<<e-b;k>0&&(o=o|a[k-1]>>this.DB+b-e)}for(j=d;(o&1)==0;){o=o>>1;--j}if((b=b-j)<0){b=b+this.DB;--k}if(n){h[o].copyTo(f);n=false}else{for(;j>1;){g.sqrTo(f,m);g.sqrTo(m,f);j=j-2}if(j>0)g.sqrTo(f,m);else{j=f;f=m;m=j}g.mulTo(m,h[o],f)}for(;k>=0&&(a[k]&1<<b)==0;){g.sqrTo(f,m);j=f;f=m;m=j;if(--b<
0){b=this.DB-1;--k}}}return g.revert(f)};e.prototype.modInverse=function(a){var c=a.isEven();if(this.isEven()&&c||a.signum()==0)return e.ZERO;for(var b=a.clone(),d=this.clone(),f=z(1),g=z(0),h=z(0),j=z(1);b.signum()!=0;){for(;b.isEven();){b.rShiftTo(1,b);if(c){if(!f.isEven()||!g.isEven()){f.addTo(this,f);g.subTo(a,g)}f.rShiftTo(1,f)}else g.isEven()||g.subTo(a,g);g.rShiftTo(1,g)}for(;d.isEven();){d.rShiftTo(1,d);if(c){if(!h.isEven()||!j.isEven()){h.addTo(this,h);j.subTo(a,j)}h.rShiftTo(1,h)}else j.isEven()||
j.subTo(a,j);j.rShiftTo(1,j)}if(b.compareTo(d)>=0){b.subTo(d,b);c&&f.subTo(h,f);g.subTo(j,g)}else{d.subTo(b,d);c&&h.subTo(f,h);j.subTo(g,j)}}if(d.compareTo(e.ONE)!=0)return e.ZERO;if(j.compareTo(a)>=0)return j.subtract(a);if(j.signum()<0)j.addTo(a,j);else return j;return j.signum()<0?j.add(a):j};e.prototype.pow=function(a){return this.exp(a,new A)};e.prototype.gcd=function(a){var c=this.s<0?this.negate():this.clone(),a=a.s<0?a.negate():a.clone();if(c.compareTo(a)<0)var b=c,c=a,a=b;var b=c.getLowestSetBit(),
d=a.getLowestSetBit();if(d<0)return c;b<d&&(d=b);if(d>0){c.rShiftTo(d,c);a.rShiftTo(d,a)}for(;c.signum()>0;){(b=c.getLowestSetBit())>0&&c.rShiftTo(b,c);(b=a.getLowestSetBit())>0&&a.rShiftTo(b,a);if(c.compareTo(a)>=0){c.subTo(a,c);c.rShiftTo(1,c)}else{a.subTo(c,a);a.rShiftTo(1,a)}}d>0&&a.lShiftTo(d,a);return a};e.prototype.isProbablePrime=function(a){var c,b=this.abs();if(b.t==1&&b[0]<=y[y.length-1]){for(c=0;c<y.length;++c)if(b[0]==y[c])return true;return false}if(b.isEven())return false;for(c=1;c<
y.length;){for(var d=y[c],f=c+1;f<y.length&&d<Y;)d=d*y[f++];for(d=b.modInt(d);c<f;)if(d%y[c++]==0)return false}return b.millerRabin(a)};e.prototype.square=function(){var a=i();this.squareTo(a);return a};H.prototype.init=function(a){var c,b,d;for(c=0;c<256;++c)this.S[c]=c;for(c=b=0;c<256;++c){b=b+this.S[c]+a[c%a.length]&255;d=this.S[c];this.S[c]=this.S[b];this.S[b]=d}this.j=this.i=0};H.prototype.next=function(){var a;this.i=this.i+1&255;this.j=this.j+this.S[this.i]&255;a=this.S[this.i];this.S[this.i]=
this.S[this.j];this.S[this.j]=a;return this.S[a+this.S[this.i]&255]};var Q,G,B;if(null==G){G=[];B=0;if(window.crypto&&window.crypto.getRandomValues){w=new Uint32Array(256);window.crypto.getRandomValues(w);for(t=0;t<w.length;++t)G[B++]=w[t]&255}var R=function(a){this.count=this.count||0;if(this.count>=256||B>=256)window.removeEventListener?window.removeEventListener("mousemove",R):window.detachEvent&&window.detachEvent("onmousemove",R);else{this.count=this.count+1;a=a.x+a.y;G[B++]=a&255}};window.addEventListener?
window.addEventListener("mousemove",R):window.attachEvent&&window.attachEvent("onmousemove",R)}D.prototype.nextBytes=function(a){var c;for(c=0;c<a.length;++c){var b=a,d=c,f;if(Q==null){for(Q=new H;B<256;){f=Math.floor(65536*Math.random());G[B++]=f&255}Q.init(G);for(B=0;B<G.length;++B)G[B]=0;B=0}f=Q.next();b[d]=f}};o.prototype.doPublic=function(a){return a.modPowInt(this.e,this.n)};o.prototype.setPublic=function(a,c){if(a!=null&&c!=null&&a.length>0&&c.length>0){this.n=l(a,16);this.e=parseInt(c,16)}else console.error("Invalid RSA public key")};
o.prototype.encrypt=function(a){var c;c=this.n.bitLength()+7>>3;if(c<a.length+11){console.error("Message too long for RSA");c=null}else{for(var b=[],d=a.length-1;d>=0&&c>0;){var f=a.charCodeAt(d--);if(f<128)b[--c]=f;else if(f>127&&f<2048){b[--c]=f&63|128;b[--c]=f>>6|192}else{b[--c]=f&63|128;b[--c]=f>>6&63|128;b[--c]=f>>12|224}}b[--c]=0;a=new D;for(d=[];c>2;){for(d[0]=0;d[0]==0;)a.nextBytes(d);b[--c]=d[0]}b[--c]=2;b[--c]=0;c=new e(b)}if(c==null)return null;c=this.doPublic(c);if(c==null)return null;
c=c.toString(16);return(c.length&1)==0?c:"0"+c};o.prototype.alipayEncrypt=function(a,c,b){for(var a=[Number(a)],d=S(c,32),f=S("",12),g=S(b,200),b=this.n.bitLength()+7>>3,c=[],a=a.concat(d).concat(f).concat(g),d=a.length-1;d>=0&&b>0;)c[--b]=a[d--];c[--b]=0;a=new D;for(d=[];b>2;){for(d[0]=0;d[0]==0;)a.nextBytes(d);c[--b]=d[0]}c[--b]=2;c[--b]=0;b=new e(c);if(b==null)return null;b=this.doPublic(b);if(b==null)return null;b=b.toString(16);return(b.length&1)==0?b:"0"+b};o.prototype.doPrivate=function(a){if(this.p==
null||this.q==null)return a.modPow(this.d,this.n);for(var c=a.mod(this.p).modPow(this.dmp1,this.p),a=a.mod(this.q).modPow(this.dmq1,this.q);c.compareTo(a)<0;)c=c.add(this.p);return c.subtract(a).multiply(this.coeff).mod(this.p).multiply(this.q).add(a)};o.prototype.setPrivate=function(a,c,b){if(a!=null&&c!=null&&a.length>0&&c.length>0){this.n=l(a,16);this.e=parseInt(c,16);this.d=l(b,16)}else console.error("Invalid RSA private key")};o.prototype.setPrivateEx=function(a,c,b,d,f,g,h,j){if(a!=null&&c!=
null&&a.length>0&&c.length>0){this.n=l(a,16);this.e=parseInt(c,16);this.d=l(b,16);this.p=l(d,16);this.q=l(f,16);this.dmp1=l(g,16);this.dmq1=l(h,16);this.coeff=l(j,16)}else console.error("Invalid RSA private key")};o.prototype.generate=function(a,c){var b=new D,d=a>>1;this.e=parseInt(c,16);for(var f=new e(c,16);;){for(;;){this.p=new e(a-d,1,b);if(this.p.subtract(e.ONE).gcd(f).compareTo(e.ONE)==0&&this.p.isProbablePrime(10))break}for(;;){this.q=new e(d,1,b);if(this.q.subtract(e.ONE).gcd(f).compareTo(e.ONE)==
0&&this.q.isProbablePrime(10))break}if(this.p.compareTo(this.q)<=0){var g=this.p;this.p=this.q;this.q=g}var g=this.p.subtract(e.ONE),h=this.q.subtract(e.ONE),j=g.multiply(h);if(j.gcd(f).compareTo(e.ONE)==0){this.n=this.p.multiply(this.q);this.d=f.modInverse(j);this.dmp1=this.d.mod(g);this.dmq1=this.d.mod(h);this.coeff=this.q.modInverse(this.p);break}}};o.prototype.decrypt=function(a){a=this.doPrivate(l(a,16));if(a==null)a=null;else a:{for(var c=this.n.bitLength()+7>>3,a=a.toByteArray(),b=0;b<a.length&&
a[b]==0;)++b;if(a.length-b!=c-1||a[b]!=2)a=null;else{for(++b;a[b]!=0;)if(++b>=a.length){a=null;break a}for(c="";++b<a.length;){var d=a[b]&255;if(d<128)c=c+String.fromCharCode(d);else if(d>191&&d<224){c=c+String.fromCharCode((d&31)<<6|a[b+1]&63);++b}else{c=c+String.fromCharCode((d&15)<<12|(a[b+1]&63)<<6|a[b+2]&63);b=b+2}}a=c}}return a};(function(){o.prototype.generateAsync=function(a,c,b){var d=new D,f=a>>1;this.e=parseInt(c,16);var g=new e(c,16),h=this,j=function(){var c=function(){if(h.p.compareTo(h.q)<=
0){var a=h.p;h.p=h.q;h.q=a}var a=h.p.subtract(e.ONE),c=h.q.subtract(e.ONE),d=a.multiply(c);if(d.gcd(g).compareTo(e.ONE)==0){h.n=h.p.multiply(h.q);h.d=g.modInverse(d);h.dmp1=h.d.mod(a);h.dmq1=h.d.mod(c);h.coeff=h.q.modInverse(h.p);setTimeout(function(){b()},0)}else setTimeout(j,0)},l=function(){h.q=i();h.q.fromNumberAsync(f,1,d,function(){h.q.subtract(e.ONE).gcda(g,function(a){a.compareTo(e.ONE)==0&&h.q.isProbablePrime(10)?setTimeout(c,0):setTimeout(l,0)})})},k=function(){h.p=i();h.p.fromNumberAsync(a-
f,1,d,function(){h.p.subtract(e.ONE).gcda(g,function(a){a.compareTo(e.ONE)==0&&h.p.isProbablePrime(10)?setTimeout(l,0):setTimeout(k,0)})})};setTimeout(k,0)};setTimeout(j,0)};e.prototype.gcda=function(a,c){var b=this.s<0?this.negate():this.clone(),d=a.s<0?a.negate():a.clone();if(b.compareTo(d)<0)var f=b,b=d,d=f;var g=b.getLowestSetBit(),h=d.getLowestSetBit();if(h<0)c(b);else{g<h&&(h=g);if(h>0){b.rShiftTo(h,b);d.rShiftTo(h,d)}var j=function(){(g=b.getLowestSetBit())>0&&b.rShiftTo(g,b);(g=d.getLowestSetBit())>
0&&d.rShiftTo(g,d);if(b.compareTo(d)>=0){b.subTo(d,b);b.rShiftTo(1,b)}else{d.subTo(b,d);d.rShiftTo(1,d)}if(b.signum()>0)setTimeout(j,0);else{h>0&&d.lShiftTo(h,d);setTimeout(function(){c(d)},0)}};setTimeout(j,10)}};e.prototype.fromNumberAsync=function(a,c,b,d){if("number"==typeof c)if(a<2)this.fromInt(1);else{this.fromNumber(a,b);this.testBit(a-1)||this.bitwiseTo(e.ONE.shiftLeft(a-1),u,this);this.isEven()&&this.dAddOffset(1,0);var f=this,g=function(){f.dAddOffset(2,0);f.bitLength()>a&&f.subTo(e.ONE.shiftLeft(a-
1),f);f.isProbablePrime(c)?setTimeout(function(){d()},0):setTimeout(g,0)};setTimeout(g,0)}else{var b=[],h=a&7;b.length=(a>>3)+1;c.nextBytes(b);b[0]=h>0?b[0]&(1<<h)-1:0;this.fromString(b,256)}}})();var L="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",V="=",m=m||{};m.env=m.env||{};var T=m,U=Object.prototype,W=["toString","valueOf"];m.env.parseUA=function(a){var c=function(a){var c=0;return parseFloat(a.replace(/\./g,function(){return c++==1?"":"."}))},b=navigator,b={ie:0,opera:0,
gecko:0,webkit:0,chrome:0,mobile:null,air:0,ipad:0,iphone:0,ipod:0,ios:null,android:0,webos:0,caja:b&&b.cajaVersion,secure:false,os:null},a=a||navigator&&navigator.userAgent,d=window&&window.location,d=d&&d.href;b.secure=d&&d.toLowerCase().indexOf("https")===0;if(a){if(/windows|win32/i.test(a))b.os="windows";else if(/macintosh/i.test(a))b.os="macintosh";else if(/rhino/i.test(a))b.os="rhino";if(/KHTML/.test(a))b.webkit=1;if((d=a.match(/AppleWebKit\/([^\s]*)/))&&d[1]){b.webkit=c(d[1]);if(/ Mobile\//.test(a)){b.mobile=
"Apple";(d=a.match(/OS ([^\s]*)/))&&d[1]&&(d=c(d[1].replace("_",".")));b.ios=d;b.ipad=b.ipod=b.iphone=0;if((d=a.match(/iPad|iPod|iPhone/))&&d[0])b[d[0].toLowerCase()]=b.ios}else{if(d=a.match(/NokiaN[^\/]*|Android \d\.\d|webOS\/\d\.\d/))b.mobile=d[0];if(/webOS/.test(a)){b.mobile="WebOS";if((d=a.match(/webOS\/([^\s]*);/))&&d[1])b.webos=c(d[1])}if(/ Android/.test(a)){b.mobile="Android";if((d=a.match(/Android ([^\s]*);/))&&d[1])b.android=c(d[1])}}if((d=a.match(/Chrome\/([^\s]*)/))&&d[1])b.chrome=c(d[1]);
else if(d=a.match(/AdobeAIR\/([^\s]*)/))b.air=d[0]}if(!b.webkit)if((d=a.match(/Opera[\s\/]([^\s]*)/))&&d[1]){b.opera=c(d[1]);if((d=a.match(/Version\/([^\s]*)/))&&d[1])b.opera=c(d[1]);if(d=a.match(/Opera Mini[^;]*/))b.mobile=d[0]}else if((d=a.match(/MSIE\s([^;]*)/))&&d[1])b.ie=c(d[1]);else if(d=a.match(/Gecko\/([^\s]*)/)){b.gecko=1;if((d=a.match(/rv:([^\s\)]*)/))&&d[1])b.gecko=c(d[1])}}return b};m.env.ua=m.env.parseUA();m.isFunction=function(a){return typeof a==="function"||U.toString.apply(a)==="[object Function]"};
m._IEEnumFix=m.env.ua.ie?function(a,c){var b,d,f;for(b=0;b<W.length;b=b+1){d=W[b];f=c[d];T.isFunction(f)&&f!=U[d]&&(a[d]=f)}}:function(){};m.extend=function(a,c,b){if(!c||!a)throw Error("extend failed, please check that all dependencies are included.");var d=function(){},f;d.prototype=c.prototype;a.prototype=new d;a.prototype.constructor=a;a.superclass=c.prototype;if(c.prototype.constructor==U.constructor)c.prototype.constructor=c;if(b){for(f in b)T.hasOwnProperty(b,f)&&(a.prototype[f]=b[f]);T._IEEnumFix(a.prototype,
b)}};if("undefined"==typeof KJUR||!KJUR)KJUR={};if("undefined"==typeof KJUR.asn1||!KJUR.asn1)KJUR.asn1={};KJUR.asn1.ASN1Util=new function(){this.integerToByteHex=function(a){a=a.toString(16);a.length%2==1&&(a="0"+a);return a};this.bigIntToMinTwosComplementsHex=function(a){var c=a.toString(16);if(c.substr(0,1)!="-")c.length%2==1?c="0"+c:c.match(/^[0-7]/)||(c="00"+c);else{var b=c.substr(1).length;b%2==1?b=b+1:c.match(/^[0-7]/)||(b=b+2);for(var c="",d=0;d<b;d++)c=c+"f";c=(new e(c,16)).xor(a).add(e.ONE).toString(16).replace(/^-/,
"")}return c};this.getPEMStringFromHex=function(a,c){var b=CryptoJS.enc.Hex.parse(a),b=CryptoJS.enc.Base64.stringify(b).replace(/(.{64})/g,"$1\r\n"),b=b.replace(/\r\n$/,"");return"-----BEGIN "+c+"-----\r\n"+b+"\r\n-----END "+c+"-----\r\n"}};KJUR.asn1.ASN1Object=function(){this.getLengthHexFromValue=function(){if(typeof this.hV=="undefined"||this.hV==null)throw"this.hV is null or undefined.";if(this.hV.length%2==1)throw"value hex must be even length: n=0,v="+this.hV;var a=this.hV.length/2,c=a.toString(16);
c.length%2==1&&(c="0"+c);if(a<128)return c;var b=c.length/2;if(b>15)throw"ASN.1 length too long to represent by 8x: n = "+a.toString(16);return(128+b).toString(16)+c};this.getEncodedHex=function(){if(this.hTLV==null||this.isModified){this.hV=this.getFreshValueHex();this.hL=this.getLengthHexFromValue();this.hTLV=this.hT+this.hL+this.hV;this.isModified=false}return this.hTLV};this.getValueHex=function(){this.getEncodedHex();return this.hV};this.getFreshValueHex=function(){return""}};KJUR.asn1.DERAbstractString=
function(a){KJUR.asn1.DERAbstractString.superclass.constructor.call(this);this.getString=function(){return this.s};this.setString=function(a){this.hTLV=null;this.isModified=true;this.s=a;this.hV=stohex(this.s)};this.setStringHex=function(a){this.hTLV=null;this.isModified=true;this.s=null;this.hV=a};this.getFreshValueHex=function(){return this.hV};typeof a!="undefined"&&(typeof a.str!="undefined"?this.setString(a.str):typeof a.hex!="undefined"&&this.setStringHex(a.hex))};m.extend(KJUR.asn1.DERAbstractString,
KJUR.asn1.ASN1Object);KJUR.asn1.DERAbstractTime=function(){KJUR.asn1.DERAbstractTime.superclass.constructor.call(this);this.localDateToUTC=function(a){utc=a.getTime()+a.getTimezoneOffset()*6E4;return new Date(utc)};this.formatDate=function(a,c){var b=this.zeroPadding,d=this.localDateToUTC(a),f=""+d.getFullYear();c=="utc"&&(f=f.substr(2,2));var g=b(""+(d.getMonth()+1),2),h=b(""+d.getDate(),2),j=b(""+d.getHours(),2),e=b(""+d.getMinutes(),2),b=b(""+d.getSeconds(),2);return f+g+h+j+e+b+"Z"};this.zeroPadding=
function(a,c){return a.length>=c?a:Array(c-a.length+1).join("0")+a};this.getString=function(){return this.s};this.setString=function(a){this.hTLV=null;this.isModified=true;this.s=a;this.hV=stohex(this.s)};this.setByDateValue=function(a,c,b,d,f,g){this.setByDate(new Date(Date.UTC(a,c-1,b,d,f,g,0)))};this.getFreshValueHex=function(){return this.hV}};m.extend(KJUR.asn1.DERAbstractTime,KJUR.asn1.ASN1Object);KJUR.asn1.DERAbstractStructured=function(a){KJUR.asn1.DERAbstractString.superclass.constructor.call(this);
this.setByASN1ObjectArray=function(a){this.hTLV=null;this.isModified=true;this.asn1Array=a};this.appendASN1Object=function(a){this.hTLV=null;this.isModified=true;this.asn1Array.push(a)};this.asn1Array=[];if(typeof a!="undefined"&&typeof a.array!="undefined")this.asn1Array=a.array};m.extend(KJUR.asn1.DERAbstractStructured,KJUR.asn1.ASN1Object);KJUR.asn1.DERBoolean=function(){KJUR.asn1.DERBoolean.superclass.constructor.call(this);this.hT="01";this.hTLV="0101ff"};m.extend(KJUR.asn1.DERBoolean,KJUR.asn1.ASN1Object);
KJUR.asn1.DERInteger=function(a){KJUR.asn1.DERInteger.superclass.constructor.call(this);this.hT="02";this.setByBigInteger=function(a){this.hTLV=null;this.isModified=true;this.hV=KJUR.asn1.ASN1Util.bigIntToMinTwosComplementsHex(a)};this.setByInteger=function(a){this.setByBigInteger(new e(""+a,10))};this.setValueHex=function(a){this.hV=a};this.getFreshValueHex=function(){return this.hV};typeof a!="undefined"&&(typeof a.bigint!="undefined"?this.setByBigInteger(a.bigint):typeof a["int"]!="undefined"?
this.setByInteger(a["int"]):typeof a.hex!="undefined"&&this.setValueHex(a.hex))};m.extend(KJUR.asn1.DERInteger,KJUR.asn1.ASN1Object);KJUR.asn1.DERBitString=function(a){KJUR.asn1.DERBitString.superclass.constructor.call(this);this.hT="03";this.setHexValueIncludingUnusedBits=function(a){this.hTLV=null;this.isModified=true;this.hV=a};this.setUnusedBitsAndHexValue=function(a,b){if(a<0||7<a)throw"unused bits shall be from 0 to 7: u = "+a;this.hTLV=null;this.isModified=true;this.hV="0"+a+b};this.setByBinaryString=
function(a){var a=a.replace(/0+$/,""),b=8-a.length%8;b==8&&(b=0);for(var d=0;d<=b;d++)a=a+"0";for(var f="",d=0;d<a.length-1;d=d+8){var g=a.substr(d,8),g=parseInt(g,2).toString(16);g.length==1&&(g="0"+g);f=f+g}this.hTLV=null;this.isModified=true;this.hV="0"+b+f};this.setByBooleanArray=function(a){for(var b="",d=0;d<a.length;d++)b=a[d]==true?b+"1":b+"0";this.setByBinaryString(b)};this.newFalseArray=function(a){for(var b=Array(a),d=0;d<a;d++)b[d]=false;return b};this.getFreshValueHex=function(){return this.hV};
typeof a!="undefined"&&(typeof a.hex!="undefined"?this.setHexValueIncludingUnusedBits(a.hex):typeof a.bin!="undefined"?this.setByBinaryString(a.bin):typeof a.array!="undefined"&&this.setByBooleanArray(a.array))};m.extend(KJUR.asn1.DERBitString,KJUR.asn1.ASN1Object);KJUR.asn1.DEROctetString=function(a){KJUR.asn1.DEROctetString.superclass.constructor.call(this,a);this.hT="04"};m.extend(KJUR.asn1.DEROctetString,KJUR.asn1.DERAbstractString);KJUR.asn1.DERNull=function(){KJUR.asn1.DERNull.superclass.constructor.call(this);
this.hT="05";this.hTLV="0500"};m.extend(KJUR.asn1.DERNull,KJUR.asn1.ASN1Object);KJUR.asn1.DERObjectIdentifier=function(a){var c=function(a){a=a.toString(16);a.length==1&&(a="0"+a);return a};KJUR.asn1.DERObjectIdentifier.superclass.constructor.call(this);this.hT="06";this.setValueHex=function(a){this.hTLV=null;this.isModified=true;this.s=null;this.hV=a};this.setValueOidString=function(a){if(!a.match(/^[0-9.]+$/))throw"malformed oid string: "+a;var d="",a=a.split("."),f=parseInt(a[0])*40+parseInt(a[1]),
d=d+c(f);a.splice(0,2);for(f=0;f<a.length;f++){var g="",h=(new e(a[f],10)).toString(2),j=7-h.length%7;j==7&&(j=0);for(var l="",i=0;i<j;i++)l=l+"0";h=l+h;for(i=0;i<h.length-1;i=i+7){j=h.substr(i,7);i!=h.length-7&&(j="1"+j);g=g+c(parseInt(j,2))}d=d+g}this.hTLV=null;this.isModified=true;this.s=null;this.hV=d};this.setValueName=function(a){if(typeof KJUR.asn1.x509.OID.name2oidList[a]!="undefined")this.setValueOidString(KJUR.asn1.x509.OID.name2oidList[a]);else throw"DERObjectIdentifier oidName undefined: "+
a;};this.getFreshValueHex=function(){return this.hV};typeof a!="undefined"&&(typeof a.oid!="undefined"?this.setValueOidString(a.oid):typeof a.hex!="undefined"?this.setValueHex(a.hex):typeof a.name!="undefined"&&this.setValueName(a.name))};m.extend(KJUR.asn1.DERObjectIdentifier,KJUR.asn1.ASN1Object);KJUR.asn1.DERUTF8String=function(a){KJUR.asn1.DERUTF8String.superclass.constructor.call(this,a);this.hT="0c"};m.extend(KJUR.asn1.DERUTF8String,KJUR.asn1.DERAbstractString);KJUR.asn1.DERNumericString=function(a){KJUR.asn1.DERNumericString.superclass.constructor.call(this,
a);this.hT="12"};m.extend(KJUR.asn1.DERNumericString,KJUR.asn1.DERAbstractString);KJUR.asn1.DERPrintableString=function(a){KJUR.asn1.DERPrintableString.superclass.constructor.call(this,a);this.hT="13"};m.extend(KJUR.asn1.DERPrintableString,KJUR.asn1.DERAbstractString);KJUR.asn1.DERTeletexString=function(a){KJUR.asn1.DERTeletexString.superclass.constructor.call(this,a);this.hT="14"};m.extend(KJUR.asn1.DERTeletexString,KJUR.asn1.DERAbstractString);KJUR.asn1.DERIA5String=function(a){KJUR.asn1.DERIA5String.superclass.constructor.call(this,
a);this.hT="16"};m.extend(KJUR.asn1.DERIA5String,KJUR.asn1.DERAbstractString);KJUR.asn1.DERUTCTime=function(a){KJUR.asn1.DERUTCTime.superclass.constructor.call(this,a);this.hT="17";this.setByDate=function(a){this.hTLV=null;this.isModified=true;this.date=a;this.s=this.formatDate(this.date,"utc");this.hV=stohex(this.s)};typeof a!="undefined"&&(typeof a.str!="undefined"?this.setString(a.str):typeof a.hex!="undefined"?this.setStringHex(a.hex):typeof a.date!="undefined"&&this.setByDate(a.date))};m.extend(KJUR.asn1.DERUTCTime,
KJUR.asn1.DERAbstractTime);KJUR.asn1.DERGeneralizedTime=function(a){KJUR.asn1.DERGeneralizedTime.superclass.constructor.call(this,a);this.hT="18";this.setByDate=function(a){this.hTLV=null;this.isModified=true;this.date=a;this.s=this.formatDate(this.date,"gen");this.hV=stohex(this.s)};typeof a!="undefined"&&(typeof a.str!="undefined"?this.setString(a.str):typeof a.hex!="undefined"?this.setStringHex(a.hex):typeof a.date!="undefined"&&this.setByDate(a.date))};m.extend(KJUR.asn1.DERGeneralizedTime,KJUR.asn1.DERAbstractTime);
KJUR.asn1.DERSequence=function(a){KJUR.asn1.DERSequence.superclass.constructor.call(this,a);this.hT="30";this.getFreshValueHex=function(){for(var a="",b=0;b<this.asn1Array.length;b++)a=a+this.asn1Array[b].getEncodedHex();return this.hV=a}};m.extend(KJUR.asn1.DERSequence,KJUR.asn1.DERAbstractStructured);KJUR.asn1.DERSet=function(a){KJUR.asn1.DERSet.superclass.constructor.call(this,a);this.hT="31";this.getFreshValueHex=function(){for(var a=[],b=0;b<this.asn1Array.length;b++)a.push(this.asn1Array[b].getEncodedHex());
a.sort();return this.hV=a.join("")}};m.extend(KJUR.asn1.DERSet,KJUR.asn1.DERAbstractStructured);KJUR.asn1.DERTaggedObject=function(a){KJUR.asn1.DERTaggedObject.superclass.constructor.call(this);this.hT="a0";this.hV="";this.isExplicit=true;this.asn1Object=null;this.setASN1Object=function(a,b,d){this.hT=b;this.isExplicit=a;this.asn1Object=d;if(this.isExplicit){this.hV=this.asn1Object.getEncodedHex();this.hTLV=null;this.isModified=true}else{this.hV=null;this.hTLV=d.getEncodedHex();this.hTLV=this.hTLV.replace(/^../,
b);this.isModified=false}};this.getFreshValueHex=function(){return this.hV};if(typeof a!="undefined"){if(typeof a.tag!="undefined")this.hT=a.tag;if(typeof a.explicit!="undefined")this.isExplicit=a.explicit;if(typeof a.obj!="undefined"){this.asn1Object=a.obj;this.setASN1Object(this.isExplicit,this.hT,this.asn1Object)}}};m.extend(KJUR.asn1.DERTaggedObject,KJUR.asn1.ASN1Object);(function(){var a={},c;a.decode=function(a){var d;if(c===void 0){var f="0123456789ABCDEF";c=[];for(d=0;d<16;++d)c[f.charAt(d)]=
d;f=f.toLowerCase();for(d=10;d<16;++d)c[f.charAt(d)]=d;for(d=0;d<8;++d)c[" \u000c\n\r\t\u00a0\u2028\u2029".charAt(d)]=-1}var f=[],g=0,h=0;for(d=0;d<a.length;++d){var j=a.charAt(d);if(j=="=")break;j=c[j];if(j!=-1){if(j===void 0)throw"Illegal character at offset "+d;g=g|j;if(++h>=2){f[f.length]=g;h=g=0}else g=g<<4}}if(h)throw"Hex encoding incomplete: 4 bits missing";return f};window.Hex=a})();(function(a){var c={},b;c.decode=function(c){var f;if(b===a){b=[];for(f=0;f<64;++f)b["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(f)]=
f;for(f=0;f<9;++f)b["= \u000c\n\r\t\u00a0\u2028\u2029".charAt(f)]=-1}var g=[],h=0,j=0;for(f=0;f<c.length;++f){var e=c.charAt(f);if(e=="=")break;e=b[e];if(e!=-1){if(e===a)throw"Illegal character at offset "+f;h=h|e;if(++j>=4){g[g.length]=h>>16;g[g.length]=h>>8&255;g[g.length]=h&255;j=h=0}else h=h<<6}}switch(j){case 1:throw"Base64 encoding incomplete: at least 2 bits missing";case 2:g[g.length]=h>>10;break;case 3:g[g.length]=h>>16;g[g.length]=h>>8&255}return g};c.re=/-----BEGIN [^-]+-----([A-Za-z0-9+\/=\s]+)-----END [^-]+-----|begin-base64[^\n]+\n([A-Za-z0-9+\/=\s]+)====/;
c.unarmor=function(a){var b=c.re.exec(a);if(b)if(b[1])a=b[1];else if(b[2])a=b[2];else throw"RegExp out of sync";return c.decode(a)};window.Base64=c})();(function(a){function c(a,b){if(a instanceof c){this.enc=a.enc;this.pos=a.pos}else{this.enc=a;this.pos=b}}function b(a,c,b,d,e){this.stream=a;this.header=c;this.length=b;this.tag=d;this.sub=e}var d={tag:function(a,c){var b=document.createElement(a);b.className=c;return b},text:function(a){return document.createTextNode(a)}};c.prototype.get=function(c){c===
a&&(c=this.pos++);if(c>=this.enc.length)throw"Requesting byte offset "+c+" on a stream of length "+this.enc.length;return this.enc[c]};c.prototype.hexDigits="0123456789ABCDEF";c.prototype.hexByte=function(a){return this.hexDigits.charAt(a>>4&15)+this.hexDigits.charAt(a&15)};c.prototype.hexDump=function(a,c,b){for(var d="";a<c;++a){d=d+this.hexByte(this.get(a));if(b!==true)switch(a&15){case 7:d=d+"  ";break;case 15:d=d+"\n";break;default:d=d+" "}}return d};c.prototype.parseStringISO=function(a,c){for(var b=
"",d=a;d<c;++d)b=b+String.fromCharCode(this.get(d));return b};c.prototype.parseStringUTF=function(a,c){for(var b="",d=a;d<c;)var e=this.get(d++),b=e<128?b+String.fromCharCode(e):e>191&&e<224?b+String.fromCharCode((e&31)<<6|this.get(d++)&63):b+String.fromCharCode((e&15)<<12|(this.get(d++)&63)<<6|this.get(d++)&63);return b};c.prototype.parseStringBMP=function(a,c){for(var b="",d=a;d<c;d=d+2)var e=this.get(d),l=this.get(d+1),b=b+String.fromCharCode((e<<8)+l);return b};c.prototype.reTime=/^((?:1[89]|2\d)?\d\d)(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])([01]\d|2[0-3])(?:([0-5]\d)(?:([0-5]\d)(?:[.,](\d{1,3}))?)?)?(Z|[-+](?:[0]\d|1[0-2])([0-5]\d)?)?$/;
c.prototype.parseTime=function(a,c){var b=this.parseStringISO(a,c),d=this.reTime.exec(b);if(!d)return"Unrecognized time: "+b;b=d[1]+"-"+d[2]+"-"+d[3]+" "+d[4];if(d[5]){b=b+(":"+d[5]);if(d[6]){b=b+(":"+d[6]);d[7]&&(b=b+("."+d[7]))}}if(d[8]){b=b+" UTC";if(d[8]!="Z"){b=b+d[8];d[9]&&(b=b+(":"+d[9]))}}return b};c.prototype.parseInteger=function(a,b){var c=b-a;if(c>4){var c=c<<3,d=this.get(a);if(d===0)c=c-8;else for(;d<128;){d=d<<1;--c}return"("+c+" bit)"}c=0;for(d=a;d<b;++d)c=c<<8|this.get(d);return c};
c.prototype.parseBitString=function(a,c){var b=this.get(a),d=(c-a-1<<3)-b,e="("+d+" bit)";if(d<=20)for(var l=b,e=e+" ",b=c-1;b>a;--b){for(d=this.get(b);l<8;++l)e=e+(d>>l&1?"1":"0");l=0}return e};c.prototype.parseOctetString=function(a,b){var c=b-a,d="("+c+" byte) ";c>100&&(b=a+100);for(var e=a;e<b;++e)d=d+this.hexByte(this.get(e));c>100&&(d=d+"\u2026");return d};c.prototype.parseOID=function(a,b){for(var c="",d=0,e=0,l=a;l<b;++l){var i=this.get(l),d=d<<7|i&127,e=e+7;if(!(i&128)){if(c===""){c=d<80?
d<40?0:1:2;c=c+"."+(d-c*40)}else c=c+("."+(e>=31?"bigint":d));d=e=0}}return c};b.prototype.typeName=function(){if(this.tag===a)return"unknown";var c=this.tag&31;switch(this.tag>>6){case 0:switch(c){case 0:return"EOC";case 1:return"BOOLEAN";case 2:return"INTEGER";case 3:return"BIT_STRING";case 4:return"OCTET_STRING";case 5:return"NULL";case 6:return"OBJECT_IDENTIFIER";case 7:return"ObjectDescriptor";case 8:return"EXTERNAL";case 9:return"REAL";case 10:return"ENUMERATED";case 11:return"EMBEDDED_PDV";
case 12:return"UTF8String";case 16:return"SEQUENCE";case 17:return"SET";case 18:return"NumericString";case 19:return"PrintableString";case 20:return"TeletexString";case 21:return"VideotexString";case 22:return"IA5String";case 23:return"UTCTime";case 24:return"GeneralizedTime";case 25:return"GraphicString";case 26:return"VisibleString";case 27:return"GeneralString";case 28:return"UniversalString";case 30:return"BMPString";default:return"Universal_"+c.toString(16)}case 1:return"Application_"+c.toString(16);
case 2:return"["+c+"]";case 3:return"Private_"+c.toString(16)}};b.prototype.reSeemsASCII=/^[ -~]+$/;b.prototype.content=function(){if(this.tag===a)return null;var c=this.tag>>6,b=this.tag&31,d=this.posContent(),e=Math.abs(this.length);if(c!==0){if(this.sub!==null)return"("+this.sub.length+" elem)";c=this.stream.parseStringISO(d,d+Math.min(e,100));return this.reSeemsASCII.test(c)?c.substring(0,200)+(c.length>200?"\u2026":""):this.stream.parseOctetString(d,d+e)}switch(b){case 1:return this.stream.get(d)===
0?"false":"true";case 2:return this.stream.parseInteger(d,d+e);case 3:return this.sub?"("+this.sub.length+" elem)":this.stream.parseBitString(d,d+e);case 4:return this.sub?"("+this.sub.length+" elem)":this.stream.parseOctetString(d,d+e);case 6:return this.stream.parseOID(d,d+e);case 16:case 17:return"("+this.sub.length+" elem)";case 12:return this.stream.parseStringUTF(d,d+e);case 18:case 19:case 20:case 21:case 22:case 26:return this.stream.parseStringISO(d,d+e);case 30:return this.stream.parseStringBMP(d,
d+e);case 23:case 24:return this.stream.parseTime(d,d+e)}return null};b.prototype.toString=function(){return this.typeName()+"@"+this.stream.pos+"[header:"+this.header+",length:"+this.length+",sub:"+(this.sub===null?"null":this.sub.length)+"]"};b.prototype.print=function(c){c===a&&(c="");document.writeln(c+this);if(this.sub!==null)for(var c=c+"  ",b=0,d=this.sub.length;b<d;++b)this.sub[b].print(c)};b.prototype.toPrettyString=function(c){c===a&&(c="");var b=c+this.typeName()+" @"+this.stream.pos;this.length>=
0&&(b=b+"+");b=b+this.length;if(this.tag&32)b=b+" (constructed)";else if((this.tag==3||this.tag==4)&&this.sub!==null)b=b+" (encapsulates)";b=b+"\n";if(this.sub!==null)for(var c=c+"  ",d=0,e=this.sub.length;d<e;++d)b=b+this.sub[d].toPrettyString(c);return b};b.prototype.toDOM=function(){var a=d.tag("div","node");a.asn1=this;var c=d.tag("div","head"),b=this.typeName().replace(/_/g," ");c.innerHTML=b;var e=this.content();if(e!==null){e=(""+e).replace(/</g,"&lt;");b=d.tag("span","preview");b.appendChild(d.text(e));
c.appendChild(b)}a.appendChild(c);this.node=a;this.head=c;var l=d.tag("div","value"),b="Offset: "+this.stream.pos+"<br/>",b=b+("Length: "+this.header+"+"),b=this.length>=0?b+this.length:b+(-this.length+" (undefined)");if(this.tag&32)b=b+"<br/>(constructed)";else if((this.tag==3||this.tag==4)&&this.sub!==null)b=b+"<br/>(encapsulates)";if(e!==null){b=b+("<br/>Value:<br/><b>"+e+"</b>");if(typeof oids==="object"&&this.tag==6)if(e=oids[e]){e.d&&(b=b+("<br/>"+e.d));e.c&&(b=b+("<br/>"+e.c));e.w&&(b=b+"<br/>(warning!)")}}l.innerHTML=
b;a.appendChild(l);b=d.tag("div","sub");if(this.sub!==null){e=0;for(l=this.sub.length;e<l;++e)b.appendChild(this.sub[e].toDOM())}a.appendChild(b);c.onclick=function(){a.className=a.className=="node collapsed"?"node":"node collapsed"};return a};b.prototype.posStart=function(){return this.stream.pos};b.prototype.posContent=function(){return this.stream.pos+this.header};b.prototype.posEnd=function(){return this.stream.pos+this.header+Math.abs(this.length)};b.prototype.fakeHover=function(a){this.node.className=
this.node.className+" hover";if(a)this.head.className=this.head.className+" hover"};b.prototype.fakeOut=function(a){var b=/ ?hover/;this.node.className=this.node.className.replace(b,"");if(a)this.head.className=this.head.className.replace(b,"")};b.prototype.toHexDOM_sub=function(a,b,c,e,l){if(!(e>=l)){b=d.tag("span",b);b.appendChild(d.text(c.hexDump(e,l)));a.appendChild(b)}};b.prototype.toHexDOM=function(b){var c=d.tag("span","hex");b===a&&(b=c);this.head.hexNode=c;this.head.onmouseover=function(){this.hexNode.className=
"hexCurrent"};this.head.onmouseout=function(){this.hexNode.className="hex"};c.asn1=this;c.onmouseover=function(){var a=!b.selected;if(a){b.selected=this.asn1;this.className="hexCurrent"}this.asn1.fakeHover(a)};c.onmouseout=function(){var a=b.selected==this.asn1;this.asn1.fakeOut(a);if(a){b.selected=null;this.className="hex"}};this.toHexDOM_sub(c,"tag",this.stream,this.posStart(),this.posStart()+1);this.toHexDOM_sub(c,this.length>=0?"dlen":"ulen",this.stream,this.posStart()+1,this.posContent());if(this.sub===
null)c.appendChild(d.text(this.stream.hexDump(this.posContent(),this.posEnd())));else if(this.sub.length>0){var e=this.sub[0],l=this.sub[this.sub.length-1];this.toHexDOM_sub(c,"intro",this.stream,this.posContent(),e.posStart());for(var e=0,i=this.sub.length;e<i;++e)c.appendChild(this.sub[e].toHexDOM(b));this.toHexDOM_sub(c,"outro",this.stream,l.posEnd(),this.posEnd())}return c};b.prototype.toHexString=function(){return this.stream.hexDump(this.posStart(),this.posEnd(),true)};b.decodeLength=function(a){var b=
a.get(),c=b&127;if(c==b)return c;if(c>3)throw"Length over 24 bits not supported at position "+(a.pos-1);if(c===0)return-1;for(var d=b=0;d<c;++d)b=b<<8|a.get();return b};b.hasContent=function(a,d,e){if(a&32)return true;if(a<3||a>4)return false;var l=new c(e);a==3&&l.get();if(l.get()>>6&1)return false;try{var i=b.decodeLength(l);return l.pos-e.pos+i==d}catch(k){return false}};b.decode=function(a){a instanceof c||(a=new c(a,0));var d=new c(a),e=a.get(),l=b.decodeLength(a),i=a.pos-d.pos,k=null;if(b.hasContent(e,
l,a)){var o=a.pos;e==3&&a.get();k=[];if(l>=0){for(var m=o+l;a.pos<m;)k[k.length]=b.decode(a);if(a.pos!=m)throw"Content size is not correct for container starting at offset "+o;}else try{for(;;){m=b.decode(a);if(m.tag===0)break;k[k.length]=m}l=o-a.pos}catch(n){throw"Exception while decoding undefined length content: "+n;}}else a.pos=a.pos+l;return new b(d,i,l,e,k)};b.test=function(){for(var a=[{value:[39],expected:39},{value:[129,201],expected:201},{value:[131,254,220,186],expected:16702650}],d=0,
e=a.length;d<e;++d){var l=new c(a[d].value,0),l=b.decodeLength(l);l!=a[d].expected&&document.write("In test["+d+"] expected "+a[d].expected+" got "+l+"\n")}};window.ASN1=b})();ASN1.prototype.getHexStringValue=function(){var a=this.header*2,c=this.length*2;return this.toHexString().substr(a,c)};o.prototype.parseKey=function(a){try{var c=/^\s*(?:[0-9A-Fa-f][0-9A-Fa-f]\s*)+$/.test(a)?Hex.decode(a):Base64.unarmor(a),b=ASN1.decode(c);if(b.sub.length===9){var d=b.sub[1].getHexStringValue();this.n=l(d,16);
var e=b.sub[2].getHexStringValue();this.e=parseInt(e,16);var g=b.sub[3].getHexStringValue();this.d=l(g,16);var h=b.sub[4].getHexStringValue();this.p=l(h,16);var i=b.sub[5].getHexStringValue();this.q=l(i,16);var k=b.sub[6].getHexStringValue();this.dmp1=l(k,16);var o=b.sub[7].getHexStringValue();this.dmq1=l(o,16);var m=b.sub[8].getHexStringValue();this.coeff=l(m,16)}else if(b.sub.length===2){var n=b.sub[1].sub[0],d=n.sub[0].getHexStringValue();this.n=l(d,16);e=n.sub[1].getHexStringValue();this.e=parseInt(e,
16)}else return false;return true}catch(p){return false}};o.prototype.getPrivateBaseKey=function(){var a={array:[new KJUR.asn1.DERInteger({"int":0}),new KJUR.asn1.DERInteger({bigint:this.n}),new KJUR.asn1.DERInteger({"int":this.e}),new KJUR.asn1.DERInteger({bigint:this.d}),new KJUR.asn1.DERInteger({bigint:this.p}),new KJUR.asn1.DERInteger({bigint:this.q}),new KJUR.asn1.DERInteger({bigint:this.dmp1}),new KJUR.asn1.DERInteger({bigint:this.dmq1}),new KJUR.asn1.DERInteger({bigint:this.coeff})]};return(new KJUR.asn1.DERSequence(a)).getEncodedHex()};
o.prototype.getPrivateBaseKeyB64=function(){return O(this.getPrivateBaseKey())};o.prototype.getPublicBaseKey=function(){var a={array:[new KJUR.asn1.DERObjectIdentifier({oid:"1.2.840.113549.1.1.1"}),new KJUR.asn1.DERNull]},c=new KJUR.asn1.DERSequence(a),a={array:[new KJUR.asn1.DERInteger({bigint:this.n}),new KJUR.asn1.DERInteger({"int":this.e})]},a={hex:"00"+(new KJUR.asn1.DERSequence(a)).getEncodedHex()},a=new KJUR.asn1.DERBitString(a),a={array:[c,a]};return(new KJUR.asn1.DERSequence(a)).getEncodedHex()};
o.prototype.getPublicBaseKeyB64=function(){return O(this.getPublicBaseKey())};o.prototype.wordwrap=function(a,c){c=c||64;return!a?a:a.match(RegExp("(.{1,"+c+"})( +|$\n?)|(.{1,"+c+"})","g")).join("\n")};o.prototype.getPrivateKey=function(){var a;a="-----BEGIN RSA PRIVATE KEY-----\n"+(this.wordwrap(this.getPrivateBaseKeyB64())+"\n");return a+"-----END RSA PRIVATE KEY-----"};o.prototype.getPublicKey=function(){var a;a="-----BEGIN PUBLIC KEY-----\n"+(this.wordwrap(this.getPublicBaseKeyB64())+"\n");return a+
"-----END PUBLIC KEY-----"};o.prototype.hasPublicKeyProperty=function(a){a=a||{};return a.hasOwnProperty("n")&&a.hasOwnProperty("e")};o.prototype.hasPrivateKeyProperty=function(a){a=a||{};return a.hasOwnProperty("n")&&a.hasOwnProperty("e")&&a.hasOwnProperty("d")&&a.hasOwnProperty("p")&&a.hasOwnProperty("q")&&a.hasOwnProperty("dmp1")&&a.hasOwnProperty("dmq1")&&a.hasOwnProperty("coeff")};o.prototype.parsePropertiesFrom=function(a){this.n=a.n;this.e=a.e;if(a.hasOwnProperty("d")){this.d=a.d;this.p=a.p;
this.q=a.q;this.dmp1=a.dmp1;this.dmq1=a.dmq1;this.coeff=a.coeff}};var M=function(a){o.call(this);a&&(typeof a==="string"?this.parseKey(a):(this.hasPrivateKeyProperty(a)||this.hasPublicKeyProperty(a))&&this.parsePropertiesFrom(a))};M.prototype=new o;M.prototype.constructor=M;m=function(a){a=a||{};this.default_key_size=parseInt(a.default_key_size)||1024;this.default_public_exponent=a.default_public_exponent||"010001";this.log=a.log||false;this.key=null};m.prototype.setKey=function(a){this.log&&this.key&&
console.warn("A key was already set, overriding existing.");this.key=new M(a)};m.prototype.setPrivateKey=function(a){this.setKey(a)};m.prototype.setPublicKey=function(a){this.setKey(a)};m.prototype.decrypt=function(a){try{return this.getKey().decrypt(X(a))}catch(c){return false}};m.prototype.encrypt=function(a){try{return O(this.getKey().encrypt(a))}catch(c){return false}};m.prototype.alipayEncrypt=function(a,c,b){try{return O(this.getKey().alipayEncrypt(a,c,b))}catch(d){return false}};m.prototype.getKey=
function(a){if(!this.key){this.key=new M;if(a&&{}.toString.call(a)==="[object Function]"){this.key.generateAsync(this.default_key_size,this.default_public_exponent,a);return}this.key.generate(this.default_key_size,this.default_public_exponent)}return this.key};m.prototype.getPrivateKey=function(){return this.getKey().getPrivateKey()};m.prototype.getPrivateKeyB64=function(){return this.getKey().getPrivateBaseKeyB64()};m.prototype.getPublicKey=function(){return this.getKey().getPublicKey()};m.prototype.getPublicKeyB64=
function(){return this.getKey().getPublicBaseKeyB64()};k.JSEncrypt=m})(alipay.security.utils);
(function(k){var e=k.Base64,i;"undefined"!==typeof module&&module.exports&&(i=require("buffer").Buffer);var p=function(e){for(var i={},k=0,n=e.length;k<n;k++)i[e.charAt(k)]=k;return i}("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"),n=String.fromCharCode,x=function(e){if(e.length<2){var i=e.charCodeAt(0);return i<128?e:i<2048?n(192|i>>>6)+n(128|i&63):n(224|i>>>12&15)+n(128|i>>>6&63)+n(128|i&63)}i=65536+(e.charCodeAt(0)-55296)*1024+(e.charCodeAt(1)-56320);return n(240|i>>>18&7)+
n(128|i>>>12&63)+n(128|i>>>6&63)+n(128|i&63)},s=/[\uD800-\uDBFF][\uDC00-\uDFFFF]|[^\x00-\x7F]/g,z=function(e){return e.replace(s,x)},J=function(e){var i=[0,2,1][e.length%3],e=e.charCodeAt(0)<<16|(e.length>1?e.charCodeAt(1):0)<<8|(e.length>2?e.charCodeAt(2):0);return["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>>18),"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>>12&63),i>=2?"=":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e>>>
6&63),i>=1?"=":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e&63)].join("")},r=k.btoa?function(e){return k.btoa(e)}:function(e){return e.replace(/[\s\S]{1,3}/g,J)},q=i?function(e){return(new i(e)).toString("base64")}:function(e){return r(z(e))},I=function(e,i){return!i?q(e):q(e).replace(/[+\/]/g,function(e){return e=="+"?"-":"_"}).replace(/=/g,"")},u=RegExp("[\u00c0-\u00df][\u0080-\u00bf]|[\u00e0-\u00ef][\u0080-\u00bf]{2}|[\u00f0-\u00f7][\u0080-\u00bf]{3}","g"),N=function(e){switch(e.length){case 4:e=
((7&e.charCodeAt(0))<<18|(63&e.charCodeAt(1))<<12|(63&e.charCodeAt(2))<<6|63&e.charCodeAt(3))-65536;return n((e>>>10)+55296)+n((e&1023)+56320);case 3:return n((15&e.charCodeAt(0))<<12|(63&e.charCodeAt(1))<<6|63&e.charCodeAt(2));default:return n((31&e.charCodeAt(0))<<6|63&e.charCodeAt(1))}},E=function(e){return e.replace(u,N)},A=function(e){var i=e.length,k=i%4,e=(i>0?p[e.charAt(0)]<<18:0)|(i>1?p[e.charAt(1)]<<12:0)|(i>2?p[e.charAt(2)]<<6:0)|(i>3?p[e.charAt(3)]:0),e=[n(e>>>16),n(e>>>8&255),n(e&255)];
e.length=e.length-[0,0,2,1][k];return e.join("")},K=k.atob?function(e){return k.atob(e)}:function(e){return e.replace(/[\s\S]{1,4}/g,A)},C=i?function(e){return(new i(e,"base64")).toString()}:function(e){return E(K(e))},H=function(e){return C(e.replace(/[-_]/g,function(e){return e=="-"?"+":"/"}).replace(/[^A-Za-z0-9\+\/]/g,""))};k.Base64={VERSION:"2.1.2",atob:K,btoa:r,fromBase64:H,toBase64:I,utob:z,encode:I,encodeURI:function(e){return I(e,true)},btou:E,decode:H,noConflict:function(){var i=k.Base64;
k.Base64=e;return i}};if("function"===typeof Object.defineProperty){var D=function(e){return{value:e,enumerable:false,writable:true,configurable:true}};k.Base64.extendString=function(){Object.defineProperty(String.prototype,"fromBase64",D(function(){return H(this)}));Object.defineProperty(String.prototype,"toBase64",D(function(e){return I(this,e)}));Object.defineProperty(String.prototype,"toBase64URI",D(function(){return I(this,true)}))}}})(alipay.security.utils);
light.has("/security/rsainput")||function(k){var e={};k.rsainput=light.deriveFrom(k.base,{ready:!0,render:function(e){light.isFunction(e)&&this._readyList.push(e);if(this.element=light.get(this.options.id)){this.element.value="";var k=this;light.on(this.element,"keydown",function(){k.result=null})}else light.log("error: rsainput element not found");light.node(this.element).attr("disabled",!1);for(e=this._readyList;e.length;)e.shift().apply(this)},postInit:function(){this._rsa=new k.utils.JSEncrypt;
this._rsa.setPublicKey(this.options.PK);this._protocolVersion="2";this._TS=k.utils.Base64.decode(this.options.TS);if(!k.edit.installed&&!k.npedit.installed){this.options.container=light.get(this.options.container);var e=this;this.onready(function(){k.edit._notInstalled.call(e)})}},getInfo:function(){return""},getCi1:function(){return""},getCi2:function(){return""},getVersion:function(){return""},getPassword:function(){if(!this.result){var i=this.element.value;if(i){var k=this._protocolVersion+this._TS+
i;this.result=e[k]||(e[k]=this._rsa.alipayEncrypt(this._protocolVersion,this._TS,i))}else this.result="";var n=this.result,x=this.element.value;this.element.value="";var s=this;setTimeout(function(){light.get(s.options.hidnId).value!=n&&(s.element.value=x,s.result=null)});setTimeout(function(){s.result=null},3E3)}return this.result}},{Name:"rsainput",installed:!0})}(alipay.security);