light.has("/alipay/security/cdo")||function(d){var e=alipay.security.downloadServer,c=function(){var c=light.client.info;return{Name:"cert.cdo",defaultMethod:"Do",info:{activex:"AliCertDO.AliCertDOCtrl",plugin:"npalicdo plugin",classId:"08d512d2-7d97-4e22-b7db-82791106c086",type:"application/npalicdo",version:"1.0.0.1",codebase:e+"/ukey/cf/alicert.cab",downloadUrl:c.os.windows?e+"/ukey/cf/alicert.exe":e+"/sec/cert/alicert.dmg"},template:c.engine.trident?'<object id="{id}" type="{type}" classid="clsid:{classId}" codebase="{codebase}" width="0" height="0"></object>':
'<object id="{id}" type="{type}" width="0" height="0"></object>',message:{"0":"\u60a8\u9700\u8981\u91cd\u65b0\u5b89\u88c5\u6570\u5b57\u8bc1\u4e66\u63a7\u4ef6",1:"\u64cd\u4f5c\u7cfb\u7edf\u6216\u6d4f\u89c8\u5668\u4e0d\u652f\u6301",2:"\u63d2\u4ef6\u6ca1\u6709\u5b89\u88c5","5001-10000":"\u60a8\u7684\u8fd0\u884c\u73af\u5883\u914d\u7f6e\u4e0d\u6b63\u786e","10001-11000":"\u63a7\u4ef6\u8fd0\u884c\u9519\u8bef","11001-12000":"\u8c03\u7528\u53c2\u6570\u9519\u8bef"},available:!!(c.os.windows||c.os.macos&&6<
c.os.macos[1]),actions:{restore:"custom"},defaults:{msgMode:"dialog"},handlers:{12004:light.noop},updateQueryInterval:1E3,updateHandler:null,properties:{handlers:{}}}}(),c=d.cdo=light.deriveFrom(d.base,{execute:function(d,a){var b=null;if(d)if("object"===typeof d?(b=d.service,d=light.param(d)):b=light.unparam(d).service,b){light.log("Calling %s: %s.",b,d);var i="";try{i=this.element.Do(d)}catch(e){light.log("Exception thrown from %s: %s.",b,g.rawData);this.catchError(b,e);return}var g=i?light.unparam(i):
{};g.rawData=i||"";g.api=b;var f=g.status=parseInt(g.status,10);isNaN(f)&&(f=-1);light.log("Result from %s: (%d) %s.",b,f,i);if(f){var j=this;101<=f&&1E3>f?(!this.backupCmd&&"update"!=b&&(this.backupCmd={command:d,callback:a}),function(){c.updateHandler&&c.updateHandler.call(j,true,g.message);setTimeout(function(){j.execute(g.rawData)},c.updateQueryInterval)}()):(this.catchError(b,g,!0),g.msg=this.getMessage(f),(b=!f?null:this.handlers[f]||this.handlers["*"]||this.__type.handlers[f]||this.__type.handlers["*"])?
b.call(this,g):this.showMessage(g))}else this.backupCmd?(c.updateHandler&&c.updateHandler.call(this,!1),b=this.backupCmd,delete this.backupCmd,light.log("Call previous command, see next log."),this.execute(b.command,b.callback)):a&&a.call(this,g)}else{if(light.debug)throw"Invalid command passed";}else if(light.debug)throw"Empty command passed";},send:function(c,a,b){a=a||{};a.service=c;a.version=1;this.execute(a,b)}},c);d.refreshStatus(c)}(alipay.security);
light.has("/alipay/security/enroll")||function(d){var e=alipay.security.downloadServer,c=light.client.info,e={activex:"Itrusenroll.CertEnroll",plugin:"iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin",classId:"7978461C-CC22-48F2-BC69-02220D3E101D",type:"application/Itrusenroll.CertEnroll.Version.1",version:"1.0.0.1",codebase:e+"/ukey/cert/1007/ie/PTA.cab",downloadUrl:e+"/ukey/cert/1007/ie/iTrusPTA.exe"},h=c.engine.trident?'<object id="{id}" type="{type}" classid="clsid:{classId}" codebase="{codebase}" width="0" height="0"></object>':
'<object id="{id}" type="{type}" width="0" height="0"></object>';availableObj={os:!!c.os.windows,browser:!!c.engine.trident||!!c.browser.firefox||!!c.browser.chrome};d.enroll=light.deriveFrom(d.base,{},{Name:"cert.enroll",defaultMethod:"Version",info:e,template:h,message:null,availableObj:availableObj,available:availableObj.os&&availableObj.browser});d.refreshStatus(d.enroll)}(alipay.security);
light.has("/alipay/security/pta")||function(d){var e=alipay.security.downloadServer,c=light.client.info,h=function(){var a={os:!!c.os.windows,browser:!(!c.engine.trident&&!c.browser.firefox&&!c.browser.chrome)};return{Name:"cert.pta",defaultMethod:"Version",info:{activex:"PTA.iTrusPTA",plugin:"iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin",classId:"1e0dffcf-27ff-4574-849b-55007349feda",type:"application/PTA.iTrusPTA.Version.1",version:"1.0.0.1",codebase:e+"/ukey/cert/1007/ie/PTA.cab",
downloadUrl:c.engine.trident?e+"/ukey/cert/1007/ie/iTrusPTA.exe?t=20110907.exe":e+"/ukey/cert/1007/ff/iTrusPTA_f_c.exe?t=20110714.exe"},template:c.engine.trident?'<object id="{id}" type="{type}" classid="clsid:{classId}" codebase="{codebase}" width="0" height="0"></object>':'<object id="{id}" type="{type}" width="0" height="0"></object>',message:{"-2147483135":"\u7528\u6237\u53d6\u6d88\u64cd\u4f5c","-2146434962":"\u7528\u6237\u53d6\u6d88\u64cd\u4f5c"},handlers:{},availableObj:a,available:a.os&&a.browser,
properties:{handlers:{}}}}();d.pta=light.deriveFrom(d.base,{getCerts:function(a,b,c){if(!a&&!b&&!c)return null;try{var d=this.api("Filter");if(!d)return null;d.Clear();a&&(8<parseInt(a.substr(0,1),16)&&(a="00"+a),d.SerialNumber=a);b&&(d.Issuer=b);c&&(d.Subject=c);return this.api("MyCertificates")}catch(e){this.catchError("filter",e)}return null},getCert:function(a,b,c){a=this.getCerts(a,b,c);b=null;a&&a.Count&&(b=a(0));return b},getCertByBlurSearch:function(a,b,c,d){if(a=this.getCert(a,b)||this.getCert(a))return a;
if(!d)return null;certs=this.getCerts("",b);for(b=0;b<certs.Count;b++)if(-1!=certs(b).Subject.indexOf(d))return certs(b);return null},sign:function(a,b,c,d,e){if(!a)throw"invalid param";b=this.getCertByBlurSearch(b,c,d,e);if(!b)return"";try{return b.SignLogonData(a,4)}catch(f){(a=!f.number?null:this.handlers[f.number]||this.handlers["*"]||this.__type.handlers[f.number]||this.__type.handlers["*"])&&a.call(this,f),this.catchError("sign",f)}return""}},h);d.refreshStatus(d.pta)}(alipay.security);
light.has("/alipay/security/hwpta")||function(d){var e=alipay.security.downloadServer,c=light.client.info,h=function(){var a={activex:"HwPTA.iTrusHwPTA",classId:"EF7BC8AC-5BDC-4AED-AD63-A9B3AE7A768C",version:"1,1,0,14",codebase:e+"/ukey/hwPTA.cab",downloadUrl:e+"/ukey/cert/1007/ie/iTrusPTA.exe?t=20110907.exe",driverUrls:{}},b={os:!!c.os.windows,browser:!!c.engine.trident};a.driverUrls["Watchdata AliPay CSP v3.3"]=e+"/ukey/0818/hwWDkey.exe";a.driverUrls["EnterSafe ePass2001 for TWCX CSP v1.0"]=e+"/ukey/0818/hwEpass2001.exe";
a.driverUrls["HaiTai Cryptographic Service Provider"]=e+"/ukey/0818/hwHaikey.exe";return{Name:"ukey.pta",defaultMethod:"DetectKeys",info:a,template:'<object id="{id}" type="{type}" classid="clsid:{classId}" codebase="{codebase}" width="0" height="0"></object>',message:null,availableObj:b,available:b.os&&b.browser}}();d.hwpta=light.deriveFrom(d.base,{checkDriver:function(){try{return this.element.checkCSP(0)}catch(a){this.catchError("checkDriver",a)}return!1},getKeyNum:function(){try{return this.element.DetectKeys()}catch(a){this.catchError("getKeyNum",
a)}return 0},getDriverName:function(a){try{return this.element.GetKeyCSPName(a||0)}catch(b){this.catchError("getDriverName",b)}return""},getDriverUrl:function(){var a=h.info.driverUrls,b=this.getDriverName(),c;for(c in a)if(b==c)return a[c];return""},deleteCert:function(a,b){try{return this.element.deleteCertificateByUserID(a,b)}catch(c){this.catchError("deleteCert",c)}return!1},importAdminPIN:function(a,b){try{return this.element.importAdminPIN(a,b)}catch(c){this.catchError("importAdminPIN",c)}return 0},
exportTempPubkey:function(){try{return this.element.exportTempPubkey()}catch(a){this.catchError("exportTempPubkey",a)}return""}},h);d.refreshStatus(d.hwpta)}(alipay.security);